<?php

/**
 * SpecimenSearch filter form base class.
 *
 * @package    darwin
 * @subpackage filter
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseSpecimenSearchFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id'                                            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'spec_ref'                                      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'category'                                      => new sfWidgetFormFilterInput(),
      'collection_ref'                                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'collection_type'                               => new sfWidgetFormFilterInput(),
      'collection_code'                               => new sfWidgetFormFilterInput(),
      'collection_name'                               => new sfWidgetFormFilterInput(),
      'collection_institution_ref'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'collection_institution_formated_name'          => new sfWidgetFormFilterInput(),
      'collection_institution_formated_name_ts'       => new sfWidgetFormFilterInput(),
      'collection_institution_formated_name_indexed'  => new sfWidgetFormFilterInput(),
      'collection_institution_sub_type'               => new sfWidgetFormFilterInput(),
      'collection_main_manager_ref'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'collection_main_manager_formated_name'         => new sfWidgetFormFilterInput(),
      'collection_main_manager_formated_name_ts'      => new sfWidgetFormFilterInput(),
      'collection_main_manager_formated_name_indexed' => new sfWidgetFormFilterInput(),
      'collection_parent_ref'                         => new sfWidgetFormFilterInput(),
      'collection_path'                               => new sfWidgetFormFilterInput(),
      'expedition_ref'                                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'expedition_name'                               => new sfWidgetFormFilterInput(),
      'expedition_name_ts'                            => new sfWidgetFormFilterInput(),
      'expedition_name_indexed'                       => new sfWidgetFormFilterInput(),
      'station_visible'                               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'gtu_ref'                                       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'gtu_code'                                      => new sfWidgetFormFilterInput(),
      'gtu_parent_ref'                                => new sfWidgetFormFilterInput(),
      'gtu_path'                                      => new sfWidgetFormFilterInput(),
      'gtu_from_date_mask'                            => new sfWidgetFormFilterInput(),
      'gtu_from_date'                                 => new sfWidgetFormFilterInput(),
      'gtu_to_date_mask'                              => new sfWidgetFormFilterInput(),
      'gtu_to_date'                                   => new sfWidgetFormFilterInput(),
      'gtu_tag_values_indexed'                        => new sfWidgetFormFilterInput(),
      'gtu_country_tag_value'                         => new sfWidgetFormFilterInput(),
      'taxon_ref'                                     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'taxon_name'                                    => new sfWidgetFormFilterInput(),
      'taxon_name_indexed'                            => new sfWidgetFormFilterInput(),
      'taxon_name_order_by'                           => new sfWidgetFormFilterInput(),
      'taxon_level_ref'                               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'taxon_level_name'                              => new sfWidgetFormFilterInput(),
      'taxon_status'                                  => new sfWidgetFormFilterInput(),
      'taxon_path'                                    => new sfWidgetFormFilterInput(),
      'taxon_parent_ref'                              => new sfWidgetFormFilterInput(),
      'taxon_extinct'                                 => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'litho_ref'                                     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'litho_name'                                    => new sfWidgetFormFilterInput(),
      'litho_name_indexed'                            => new sfWidgetFormFilterInput(),
      'litho_name_order_by'                           => new sfWidgetFormFilterInput(),
      'litho_level_ref'                               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'litho_level_name'                              => new sfWidgetFormFilterInput(),
      'litho_status'                                  => new sfWidgetFormFilterInput(),
      'litho_path'                                    => new sfWidgetFormFilterInput(),
      'litho_parent_ref'                              => new sfWidgetFormFilterInput(),
      'chrono_ref'                                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'chrono_name'                                   => new sfWidgetFormFilterInput(),
      'chrono_name_indexed'                           => new sfWidgetFormFilterInput(),
      'chrono_name_order_by'                          => new sfWidgetFormFilterInput(),
      'chrono_level_ref'                              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'chrono_level_name'                             => new sfWidgetFormFilterInput(),
      'chrono_status'                                 => new sfWidgetFormFilterInput(),
      'chrono_path'                                   => new sfWidgetFormFilterInput(),
      'chrono_parent_ref'                             => new sfWidgetFormFilterInput(),
      'lithology_ref'                                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'lithology_name'                                => new sfWidgetFormFilterInput(),
      'lithology_name_indexed'                        => new sfWidgetFormFilterInput(),
      'lithology_name_order_by'                       => new sfWidgetFormFilterInput(),
      'lithology_level_ref'                           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'lithology_level_name'                          => new sfWidgetFormFilterInput(),
      'lithology_status'                              => new sfWidgetFormFilterInput(),
      'lithology_path'                                => new sfWidgetFormFilterInput(),
      'lithology_parent_ref'                          => new sfWidgetFormFilterInput(),
      'mineral_ref'                                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'mineral_name'                                  => new sfWidgetFormFilterInput(),
      'mineral_name_indexed'                          => new sfWidgetFormFilterInput(),
      'mineral_name_order_by'                         => new sfWidgetFormFilterInput(),
      'mineral_level_ref'                             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'mineral_level_name'                            => new sfWidgetFormFilterInput(),
      'mineral_status'                                => new sfWidgetFormFilterInput(),
      'mineral_path'                                  => new sfWidgetFormFilterInput(),
      'mineral_parent_ref'                            => new sfWidgetFormFilterInput(),
      'host_taxon_ref'                                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'host_relationship'                             => new sfWidgetFormFilterInput(),
      'host_taxon_name'                               => new sfWidgetFormFilterInput(),
      'host_taxon_name_indexed'                       => new sfWidgetFormFilterInput(),
      'host_taxon_name_order_by'                      => new sfWidgetFormFilterInput(),
      'host_taxon_level_ref'                          => new sfWidgetFormFilterInput(),
      'host_taxon_level_name'                         => new sfWidgetFormFilterInput(),
      'host_taxon_status'                             => new sfWidgetFormFilterInput(),
      'host_taxon_path'                               => new sfWidgetFormFilterInput(),
      'host_taxon_parent_ref'                         => new sfWidgetFormFilterInput(),
      'host_taxon_extinct'                            => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'ig_ref'                                        => new sfWidgetFormFilterInput(),
      'ig_num'                                        => new sfWidgetFormFilterInput(),
      'ig_num_indexed'                                => new sfWidgetFormFilterInput(),
      'ig_date_mask'                                  => new sfWidgetFormFilterInput(),
      'ig_date'                                       => new sfWidgetFormFilterInput(),
      'acquisition_category'                          => new sfWidgetFormFilterInput(),
      'acquisition_date_mask'                         => new sfWidgetFormFilterInput(),
      'acquisition_date'                              => new sfWidgetFormFilterInput(),
      'specimen_count_min'                            => new sfWidgetFormFilterInput(),
      'specimen_count_max'                            => new sfWidgetFormFilterInput(),
      'with_types'                                    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
    ));

    $this->setValidators(array(
      'id'                                            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'spec_ref'                                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'category'                                      => new sfValidatorPass(array('required' => false)),
      'collection_ref'                                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'collection_type'                               => new sfValidatorPass(array('required' => false)),
      'collection_code'                               => new sfValidatorPass(array('required' => false)),
      'collection_name'                               => new sfValidatorPass(array('required' => false)),
      'collection_institution_ref'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'collection_institution_formated_name'          => new sfValidatorPass(array('required' => false)),
      'collection_institution_formated_name_ts'       => new sfValidatorPass(array('required' => false)),
      'collection_institution_formated_name_indexed'  => new sfValidatorPass(array('required' => false)),
      'collection_institution_sub_type'               => new sfValidatorPass(array('required' => false)),
      'collection_main_manager_ref'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'collection_main_manager_formated_name'         => new sfValidatorPass(array('required' => false)),
      'collection_main_manager_formated_name_ts'      => new sfValidatorPass(array('required' => false)),
      'collection_main_manager_formated_name_indexed' => new sfValidatorPass(array('required' => false)),
      'collection_parent_ref'                         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'collection_path'                               => new sfValidatorPass(array('required' => false)),
      'expedition_ref'                                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'expedition_name'                               => new sfValidatorPass(array('required' => false)),
      'expedition_name_ts'                            => new sfValidatorPass(array('required' => false)),
      'expedition_name_indexed'                       => new sfValidatorPass(array('required' => false)),
      'station_visible'                               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'gtu_ref'                                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gtu_code'                                      => new sfValidatorPass(array('required' => false)),
      'gtu_parent_ref'                                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gtu_path'                                      => new sfValidatorPass(array('required' => false)),
      'gtu_from_date_mask'                            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gtu_from_date'                                 => new sfValidatorPass(array('required' => false)),
      'gtu_to_date_mask'                              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gtu_to_date'                                   => new sfValidatorPass(array('required' => false)),
      'gtu_tag_values_indexed'                        => new sfValidatorPass(array('required' => false)),
      'gtu_country_tag_value'                         => new sfValidatorPass(array('required' => false)),
      'taxon_ref'                                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'taxon_name'                                    => new sfValidatorPass(array('required' => false)),
      'taxon_name_indexed'                            => new sfValidatorPass(array('required' => false)),
      'taxon_name_order_by'                           => new sfValidatorPass(array('required' => false)),
      'taxon_level_ref'                               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'taxon_level_name'                              => new sfValidatorPass(array('required' => false)),
      'taxon_status'                                  => new sfValidatorPass(array('required' => false)),
      'taxon_path'                                    => new sfValidatorPass(array('required' => false)),
      'taxon_parent_ref'                              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'taxon_extinct'                                 => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'litho_ref'                                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'litho_name'                                    => new sfValidatorPass(array('required' => false)),
      'litho_name_indexed'                            => new sfValidatorPass(array('required' => false)),
      'litho_name_order_by'                           => new sfValidatorPass(array('required' => false)),
      'litho_level_ref'                               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'litho_level_name'                              => new sfValidatorPass(array('required' => false)),
      'litho_status'                                  => new sfValidatorPass(array('required' => false)),
      'litho_path'                                    => new sfValidatorPass(array('required' => false)),
      'litho_parent_ref'                              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'chrono_ref'                                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'chrono_name'                                   => new sfValidatorPass(array('required' => false)),
      'chrono_name_indexed'                           => new sfValidatorPass(array('required' => false)),
      'chrono_name_order_by'                          => new sfValidatorPass(array('required' => false)),
      'chrono_level_ref'                              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'chrono_level_name'                             => new sfValidatorPass(array('required' => false)),
      'chrono_status'                                 => new sfValidatorPass(array('required' => false)),
      'chrono_path'                                   => new sfValidatorPass(array('required' => false)),
      'chrono_parent_ref'                             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'lithology_ref'                                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'lithology_name'                                => new sfValidatorPass(array('required' => false)),
      'lithology_name_indexed'                        => new sfValidatorPass(array('required' => false)),
      'lithology_name_order_by'                       => new sfValidatorPass(array('required' => false)),
      'lithology_level_ref'                           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'lithology_level_name'                          => new sfValidatorPass(array('required' => false)),
      'lithology_status'                              => new sfValidatorPass(array('required' => false)),
      'lithology_path'                                => new sfValidatorPass(array('required' => false)),
      'lithology_parent_ref'                          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mineral_ref'                                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mineral_name'                                  => new sfValidatorPass(array('required' => false)),
      'mineral_name_indexed'                          => new sfValidatorPass(array('required' => false)),
      'mineral_name_order_by'                         => new sfValidatorPass(array('required' => false)),
      'mineral_level_ref'                             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mineral_level_name'                            => new sfValidatorPass(array('required' => false)),
      'mineral_status'                                => new sfValidatorPass(array('required' => false)),
      'mineral_path'                                  => new sfValidatorPass(array('required' => false)),
      'mineral_parent_ref'                            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'host_taxon_ref'                                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'host_relationship'                             => new sfValidatorPass(array('required' => false)),
      'host_taxon_name'                               => new sfValidatorPass(array('required' => false)),
      'host_taxon_name_indexed'                       => new sfValidatorPass(array('required' => false)),
      'host_taxon_name_order_by'                      => new sfValidatorPass(array('required' => false)),
      'host_taxon_level_ref'                          => new sfValidatorPass(array('required' => false)),
      'host_taxon_level_name'                         => new sfValidatorPass(array('required' => false)),
      'host_taxon_status'                             => new sfValidatorPass(array('required' => false)),
      'host_taxon_path'                               => new sfValidatorPass(array('required' => false)),
      'host_taxon_parent_ref'                         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'host_taxon_extinct'                            => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'ig_ref'                                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ig_num'                                        => new sfValidatorPass(array('required' => false)),
      'ig_num_indexed'                                => new sfValidatorPass(array('required' => false)),
      'ig_date_mask'                                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ig_date'                                       => new sfValidatorPass(array('required' => false)),
      'acquisition_category'                          => new sfValidatorPass(array('required' => false)),
      'acquisition_date_mask'                         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'acquisition_date'                              => new sfValidatorPass(array('required' => false)),
      'specimen_count_min'                            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'specimen_count_max'                            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'with_types'                                    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
    ));

    $this->widgetSchema->setNameFormat('specimen_search_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'SpecimenSearch';
  }

  public function getFields()
  {
    return array(
      'id'                                            => 'Number',
      'spec_ref'                                      => 'Number',
      'category'                                      => 'Text',
      'collection_ref'                                => 'Number',
      'collection_type'                               => 'Text',
      'collection_code'                               => 'Text',
      'collection_name'                               => 'Text',
      'collection_institution_ref'                    => 'Number',
      'collection_institution_formated_name'          => 'Text',
      'collection_institution_formated_name_ts'       => 'Text',
      'collection_institution_formated_name_indexed'  => 'Text',
      'collection_institution_sub_type'               => 'Text',
      'collection_main_manager_ref'                   => 'Number',
      'collection_main_manager_formated_name'         => 'Text',
      'collection_main_manager_formated_name_ts'      => 'Text',
      'collection_main_manager_formated_name_indexed' => 'Text',
      'collection_parent_ref'                         => 'Number',
      'collection_path'                               => 'Text',
      'expedition_ref'                                => 'Number',
      'expedition_name'                               => 'Text',
      'expedition_name_ts'                            => 'Text',
      'expedition_name_indexed'                       => 'Text',
      'station_visible'                               => 'Boolean',
      'gtu_ref'                                       => 'Number',
      'gtu_code'                                      => 'Text',
      'gtu_parent_ref'                                => 'Number',
      'gtu_path'                                      => 'Text',
      'gtu_from_date_mask'                            => 'Number',
      'gtu_from_date'                                 => 'Text',
      'gtu_to_date_mask'                              => 'Number',
      'gtu_to_date'                                   => 'Text',
      'gtu_tag_values_indexed'                        => 'Text',
      'gtu_country_tag_value'                         => 'Text',
      'taxon_ref'                                     => 'Number',
      'taxon_name'                                    => 'Text',
      'taxon_name_indexed'                            => 'Text',
      'taxon_name_order_by'                           => 'Text',
      'taxon_level_ref'                               => 'Number',
      'taxon_level_name'                              => 'Text',
      'taxon_status'                                  => 'Text',
      'taxon_path'                                    => 'Text',
      'taxon_parent_ref'                              => 'Number',
      'taxon_extinct'                                 => 'Boolean',
      'litho_ref'                                     => 'Number',
      'litho_name'                                    => 'Text',
      'litho_name_indexed'                            => 'Text',
      'litho_name_order_by'                           => 'Text',
      'litho_level_ref'                               => 'Number',
      'litho_level_name'                              => 'Text',
      'litho_status'                                  => 'Text',
      'litho_path'                                    => 'Text',
      'litho_parent_ref'                              => 'Number',
      'chrono_ref'                                    => 'Number',
      'chrono_name'                                   => 'Text',
      'chrono_name_indexed'                           => 'Text',
      'chrono_name_order_by'                          => 'Text',
      'chrono_level_ref'                              => 'Number',
      'chrono_level_name'                             => 'Text',
      'chrono_status'                                 => 'Text',
      'chrono_path'                                   => 'Text',
      'chrono_parent_ref'                             => 'Number',
      'lithology_ref'                                 => 'Number',
      'lithology_name'                                => 'Text',
      'lithology_name_indexed'                        => 'Text',
      'lithology_name_order_by'                       => 'Text',
      'lithology_level_ref'                           => 'Number',
      'lithology_level_name'                          => 'Text',
      'lithology_status'                              => 'Text',
      'lithology_path'                                => 'Text',
      'lithology_parent_ref'                          => 'Number',
      'mineral_ref'                                   => 'Number',
      'mineral_name'                                  => 'Text',
      'mineral_name_indexed'                          => 'Text',
      'mineral_name_order_by'                         => 'Text',
      'mineral_level_ref'                             => 'Number',
      'mineral_level_name'                            => 'Text',
      'mineral_status'                                => 'Text',
      'mineral_path'                                  => 'Text',
      'mineral_parent_ref'                            => 'Number',
      'host_taxon_ref'                                => 'Number',
      'host_relationship'                             => 'Text',
      'host_taxon_name'                               => 'Text',
      'host_taxon_name_indexed'                       => 'Text',
      'host_taxon_name_order_by'                      => 'Text',
      'host_taxon_level_ref'                          => 'Text',
      'host_taxon_level_name'                         => 'Text',
      'host_taxon_status'                             => 'Text',
      'host_taxon_path'                               => 'Text',
      'host_taxon_parent_ref'                         => 'Number',
      'host_taxon_extinct'                            => 'Boolean',
      'ig_ref'                                        => 'Number',
      'ig_num'                                        => 'Text',
      'ig_num_indexed'                                => 'Text',
      'ig_date_mask'                                  => 'Number',
      'ig_date'                                       => 'Text',
      'acquisition_category'                          => 'Text',
      'acquisition_date_mask'                         => 'Number',
      'acquisition_date'                              => 'Text',
      'specimen_count_min'                            => 'Number',
      'specimen_count_max'                            => 'Number',
      'with_types'                                    => 'Boolean',
    );
  }
}
