<?php

/**
 * BaseSpecimensRelationships
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $specimen_ref
 * @property integer $taxon_ref
 * @property integer $mineral_ref
 * @property integer $specimen_related_ref
 * @property string $relationship_type
 * @property string $unit_type
 * @property decimal $quantity
 * @property string $unit
 * @property integer $institution_ref
 * @property string $source_name
 * @property string $source_id
 * @property Specimens $Specimen
 * @property Specimens $SpecimenRelated
 * @property Taxonomy $Taxonomy
 * @property Mineralogy $Mineralogy
 * @property Institutions $Institutions
 * 
 * @method integer                getSpecimenRef()          Returns the current record's "specimen_ref" value
 * @method integer                getTaxonRef()             Returns the current record's "taxon_ref" value
 * @method integer                getMineralRef()           Returns the current record's "mineral_ref" value
 * @method integer                getSpecimenRelatedRef()   Returns the current record's "specimen_related_ref" value
 * @method string                 getRelationshipType()     Returns the current record's "relationship_type" value
 * @method string                 getUnitType()             Returns the current record's "unit_type" value
 * @method decimal                getQuantity()             Returns the current record's "quantity" value
 * @method string                 getUnit()                 Returns the current record's "unit" value
 * @method integer                getInstitutionRef()       Returns the current record's "institution_ref" value
 * @method string                 getSourceName()           Returns the current record's "source_name" value
 * @method string                 getSourceId()             Returns the current record's "source_id" value
 * @method Specimens              getSpecimen()             Returns the current record's "Specimen" value
 * @method Specimens              getSpecimenRelated()      Returns the current record's "SpecimenRelated" value
 * @method Taxonomy               getTaxonomy()             Returns the current record's "Taxonomy" value
 * @method Mineralogy             getMineralogy()           Returns the current record's "Mineralogy" value
 * @method Institutions           getInstitutions()         Returns the current record's "Institutions" value
 * @method SpecimensRelationships setSpecimenRef()          Sets the current record's "specimen_ref" value
 * @method SpecimensRelationships setTaxonRef()             Sets the current record's "taxon_ref" value
 * @method SpecimensRelationships setMineralRef()           Sets the current record's "mineral_ref" value
 * @method SpecimensRelationships setSpecimenRelatedRef()   Sets the current record's "specimen_related_ref" value
 * @method SpecimensRelationships setRelationshipType()     Sets the current record's "relationship_type" value
 * @method SpecimensRelationships setUnitType()             Sets the current record's "unit_type" value
 * @method SpecimensRelationships setQuantity()             Sets the current record's "quantity" value
 * @method SpecimensRelationships setUnit()                 Sets the current record's "unit" value
 * @method SpecimensRelationships setInstitutionRef()       Sets the current record's "institution_ref" value
 * @method SpecimensRelationships setSourceName()           Sets the current record's "source_name" value
 * @method SpecimensRelationships setSourceId()             Sets the current record's "source_id" value
 * @method SpecimensRelationships setSpecimen()             Sets the current record's "Specimen" value
 * @method SpecimensRelationships setSpecimenRelated()      Sets the current record's "SpecimenRelated" value
 * @method SpecimensRelationships setTaxonomy()             Sets the current record's "Taxonomy" value
 * @method SpecimensRelationships setMineralogy()           Sets the current record's "Mineralogy" value
 * @method SpecimensRelationships setInstitutions()         Sets the current record's "Institutions" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpecimensRelationships extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('specimens_relationships');
        $this->hasColumn('specimen_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('taxon_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mineral_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('specimen_related_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('relationship_type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'host',
             ));
        $this->hasColumn('unit_type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'specimens',
             ));
        $this->hasColumn('quantity', 'decimal', 16, array(
             'type' => 'decimal',
             'length' => 16,
             'scale' => 2,
             ));
        $this->hasColumn('unit', 'string', null, array(
             'type' => 'string',
             'default' => '%',
             ));
        $this->hasColumn('institution_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('source_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('source_id', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Specimens as Specimen', array(
             'local' => 'specimen_ref',
             'foreign' => 'id'));

        $this->hasOne('Specimens as SpecimenRelated', array(
             'local' => 'specimen_related_ref',
             'foreign' => 'id'));

        $this->hasOne('Taxonomy', array(
             'local' => 'taxon_ref',
             'foreign' => 'id'));

        $this->hasOne('Mineralogy', array(
             'local' => 'mineral_ref',
             'foreign' => 'id'));

        $this->hasOne('Institutions', array(
             'local' => 'institution_ref',
             'foreign' => 'id'));
    }
}
