<?php

/**
 * BaseUsersWorkflow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $referenced_relation
 * @property integer $record_id
 * @property integer $user_ref
 * @property string $status
 * @property string $modification_date_time
 * @property string $comment
 * @property Users $Users
 * 
 * @method integer       getId()                     Returns the current record's "id" value
 * @method string        getReferencedRelation()     Returns the current record's "referenced_relation" value
 * @method integer       getRecordId()               Returns the current record's "record_id" value
 * @method integer       getUserRef()                Returns the current record's "user_ref" value
 * @method string        getStatus()                 Returns the current record's "status" value
 * @method string        getModificationDateTime()   Returns the current record's "modification_date_time" value
 * @method string        getComment()                Returns the current record's "comment" value
 * @method Users         getUsers()                  Returns the current record's "Users" value
 * @method UsersWorkflow setId()                     Sets the current record's "id" value
 * @method UsersWorkflow setReferencedRelation()     Sets the current record's "referenced_relation" value
 * @method UsersWorkflow setRecordId()               Sets the current record's "record_id" value
 * @method UsersWorkflow setUserRef()                Sets the current record's "user_ref" value
 * @method UsersWorkflow setStatus()                 Sets the current record's "status" value
 * @method UsersWorkflow setModificationDateTime()   Sets the current record's "modification_date_time" value
 * @method UsersWorkflow setComment()                Sets the current record's "comment" value
 * @method UsersWorkflow setUsers()                  Sets the current record's "Users" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsersWorkflow extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('users_workflow');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('referenced_relation', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('record_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'to check',
             ));
        $this->hasColumn('modification_date_time', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('comment', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users', array(
             'local' => 'user_ref',
             'foreign' => 'id'));
    }
}