<?php

/**
 * BaseLoans
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $status
 * @property string $to_date
 * @property string $effective_to_date
 * @property Doctrine_Collection $LoanItems
 * @property Doctrine_Collection $LoanRights
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method string              getStatus()            Returns the current record's "status" value
 * @method string              getToDate()            Returns the current record's "to_date" value
 * @method string              getEffectiveToDate()   Returns the current record's "effective_to_date" value
 * @method Doctrine_Collection getLoanItems()         Returns the current record's "LoanItems" collection
 * @method Doctrine_Collection getLoanRights()        Returns the current record's "LoanRights" collection
 * @method Loans               setId()                Sets the current record's "id" value
 * @method Loans               setName()              Sets the current record's "name" value
 * @method Loans               setDescription()       Sets the current record's "description" value
 * @method Loans               setStatus()            Sets the current record's "status" value
 * @method Loans               setToDate()            Sets the current record's "to_date" value
 * @method Loans               setEffectiveToDate()   Sets the current record's "effective_to_date" value
 * @method Loans               setLoanItems()         Sets the current record's "LoanItems" collection
 * @method Loans               setLoanRights()        Sets the current record's "LoanRights" collection
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLoans extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('loans');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             ));
        $this->hasColumn('status', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'new',
             ));
        $this->hasColumn('to_date', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('effective_to_date', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('LoanItems', array(
             'local' => 'id',
             'foreign' => 'loan_ref'));

        $this->hasMany('LoanRights', array(
             'local' => 'id',
             'foreign' => 'loan_ref'));
    }
}