<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePossibleUpperLevels extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('possible_upper_levels');
        $this->hasColumn('level_ref', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('level_upper_ref', 'integer', null, array('type' => 'integer', 'notnull' => true));
    }

    public function setUp()
    {
        $this->hasOne('CatalogueLevels as UpperLevel', array('local' => 'level_upper_ref',
                                                             'foreign' => 'id'));

        $this->hasOne('CatalogueLevels as Level', array('local' => 'level_ref',
                                                        'foreign' => 'id'));
    }
}