<?php

/**
 * BaseSoortenregister
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $taxa_ref
 * @property integer $gtu_ref
 * @property integer $habitat_ref
 * @property date $date_from
 * @property date $date_to
 * @property Taxonomy $Taxonomy
 * @property Gtu $Gtu
 * @property Habitats $Habitats
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
abstract class BaseSoortenregister extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('soortenregister');
        $this->hasColumn('taxa_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('gtu_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('habitat_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('date_from', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('date_to', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Taxonomy', array(
             'local' => 'taxa_ref',
             'foreign' => 'id'));

        $this->hasOne('Gtu', array(
             'local' => 'gtu_ref',
             'foreign' => 'id'));

        $this->hasOne('Habitats', array(
             'local' => 'habitat_ref',
             'foreign' => 'id'));
    }
}