<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseChronostratigraphy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chronostratigraphy');
        $this->hasColumn('id', 'integer', null, array('type' => 'integer', 'primary' => true));
        $this->hasColumn('name', 'string', null, array('type' => 'string', 'notnull' => true));
        $this->hasColumn('name_indexed', 'string', null, array('type' => 'string'));
        $this->hasColumn('description_year', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('description_year_compl', 'string', 2, array('type' => 'string', 'length' => '2'));
        $this->hasColumn('level_ref', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('status', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => 'valid'));
        $this->hasColumn('path', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => '/'));
        $this->hasColumn('parent_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('eon_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('eon_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('era_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('era_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('sub_era_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('sub_era_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('system_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('system_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('serie_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('serie_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('stage_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('stage_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('sub_stage_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('sub_stage_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('sub_level_1_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('sub_level_1_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('sub_level_2_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('sub_level_2_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('lower_bound', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('upper_bound', 'integer', null, array('type' => 'integer'));
    }

    public function setUp()
    {
        $this->hasOne('Chronostratigraphy as Parent', array('local' => 'parent_ref',
                                                            'foreign' => 'id'));

        $this->hasMany('Chronostratigraphy', array('local' => 'id',
                                                   'foreign' => 'parent_ref'));

        $this->hasMany('Specimens', array('local' => 'id',
                                          'foreign' => 'chrono_ref'));
    }
}