<?php

/**
 * BasePeopleRelationships
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $relationship_type
 * @property integer $person_1_ref
 * @property integer $person_2_ref
 * @property string $person_title
 * @property string $path
 * @property string $organization_unit
 * @property string $person_user_role
 * @property string $activity_period
 * @property People $People1
 * @property People $People2
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
abstract class BasePeopleRelationships extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('people_relationships');
        $this->hasColumn('relationship_type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'belongs to',
             ));
        $this->hasColumn('person_1_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('person_2_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('person_title', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('path', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('organization_unit', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('person_user_role', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('activity_period', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('People as People1', array(
             'local' => 'person_1_ref',
             'foreign' => 'id'));

        $this->hasOne('People as People2', array(
             'local' => 'person_2_ref',
             'foreign' => 'id'));
    }
}