<?php

/**
 * BaseExpeditions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $name_ts
 * @property string $name_indexed
 * @property string $name_language_full_text
 * @property integer $expedition_from_date_mask
 * @property date $expedition_from_date
 * @property integer $expedition_to_date_mask
 * @property date $expedition_to_date
 * @property Doctrine_Collection $Specimens
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class BaseExpeditions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('expeditions');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('name_ts', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('name_indexed', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('name_language_full_text', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('expedition_from_date_mask', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('expedition_from_date', 'date', null, array(
             'type' => 'date',
             'default' => '0001-01-01',
             ));
        $this->hasColumn('expedition_to_date_mask', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('expedition_to_date', 'date', null, array(
             'type' => 'date',
             'default' => '0001-01-01',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Specimens', array(
             'local' => 'id',
             'foreign' => 'expedition_ref'));
    }
}