<?php

/**
 * BaseHabitats
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $path
 * @property string $code
 * @property string $code_indexed
 * @property string $description
 * @property string $description_ts
 * @property string $description_language_full_text
 * @property string $habitat_system
 * @property Doctrine_Collection $Soortenregister
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class BaseHabitats extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('habitats');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('path', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '/',
             ));
        $this->hasColumn('code', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('code_indexed', 'string', null, array(
             'type' => 'string',
             'default' => '/',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('description_ts', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('description_language_full_text', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('habitat_system', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'eunis',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Soortenregister', array(
             'local' => 'id',
             'foreign' => 'habitat_ref'));
    }
}