<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePeopleLanguages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('people_languages');
        $this->hasColumn('people_ref', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('language_country', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => 'en_gb'));
        $this->hasColumn('mother', 'boolean', null, array('type' => 'boolean', 'notnull' => true, 'default' => true));
        $this->hasColumn('prefered_language', 'boolean', null, array('type' => 'boolean', 'notnull' => true, 'default' => false));
    }

    public function setUp()
    {
        $this->hasOne('People', array('local' => 'people_ref',
                                      'foreign' => 'id'));
    }
}