<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUsersMultimedia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('users_multimedia');
        $this->hasColumn('person_user_ref', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('object_ref', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('category', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => 'avatar'));
    }

    public function setUp()
    {
        $this->hasOne('Users', array('local' => 'person_user_ref',
                                     'foreign' => 'id'));

        $this->hasOne('Multimedia', array('local' => 'object_ref',
                                          'foreign' => 'id'));
    }
}