<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMultimedia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('multimedia');
        $this->hasColumn('id', 'integer', null, array('type' => 'integer', 'primary' => true));
        $this->hasColumn('is_digital', 'boolean', null, array('type' => 'boolean', 'notnull' => true));
        $this->hasColumn('type', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => 'image'));
        $this->hasColumn('sub_type', 'string', null, array('type' => 'string'));
        $this->hasColumn('title', 'string', null, array('type' => 'string', 'notnull' => true));
        $this->hasColumn('title_indexed', 'string', null, array('type' => 'string'));
        $this->hasColumn('subject', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => '/'));
        $this->hasColumn('coverage', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => 'temporal'));
        $this->hasColumn('apercu_path', 'string', null, array('type' => 'string'));
        $this->hasColumn('copyright', 'string', null, array('type' => 'string'));
        $this->hasColumn('license', 'string', null, array('type' => 'string'));
        $this->hasColumn('uri', 'string', null, array('type' => 'string'));
        $this->hasColumn('descriptive_ts', 'string', null, array('type' => 'string'));
        $this->hasColumn('descriptive_language_full_text', 'string', null, array('type' => 'string'));
        $this->hasColumn('creation_date', 'date', null, array('type' => 'date', 'notnull' => true, 'default' => '01/01/4713BC'));
        $this->hasColumn('creation_date_mask', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('publication_date_from', 'date', null, array('type' => 'date', 'notnull' => true, 'default' => '01/01/4713BC'));
        $this->hasColumn('publication_date_from_mask', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('publication_date_to', 'date', null, array('type' => 'date', 'notnull' => true, 'default' => '01/01/4713BC'));
        $this->hasColumn('publication_date_to_mask', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('parent_ref', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('path', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => '/'));
        $this->hasColumn('mime_type', 'string', null, array('type' => 'string'));
    }

    public function setUp()
    {
        $this->hasOne('Multimedia as Parent', array('local' => 'parent_ref',
                                                    'foreign' => 'id'));

        $this->hasMany('Multimedia', array('local' => 'id',
                                           'foreign' => 'parent_ref'));

        $this->hasMany('PeopleMultimedia', array('local' => 'id',
                                                 'foreign' => 'object_ref'));

        $this->hasMany('UsersMultimedia', array('local' => 'id',
                                                'foreign' => 'object_ref'));

        $this->hasMany('MyPreferences', array('local' => 'id',
                                              'foreign' => 'icon_ref'));

        $this->hasMany('MultimediaKeywords', array('local' => 'id',
                                                   'foreign' => 'object_ref'));

        $this->hasMany('AssociatedMultimedia', array('local' => 'id',
                                                     'foreign' => 'multimedia_ref'));
    }
}