<?php

/**
 * BasePeopleMultimedia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $person_user_ref
 * @property integer $object_ref
 * @property string $category
 * @property People $People
 * @property Multimedia $Multimedia
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
abstract class BasePeopleMultimedia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('people_multimedia');
        $this->hasColumn('person_user_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('object_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('category', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'avatar',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('People', array(
             'local' => 'person_user_ref',
             'foreign' => 'id'));

        $this->hasOne('Multimedia', array(
             'local' => 'object_ref',
             'foreign' => 'id'));
    }
}