<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCatalogueLevels extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('catalogue_levels');
        $this->hasColumn('id', 'integer', null, array('type' => 'integer', 'primary' => true));
        $this->hasColumn('level_type', 'string', null, array('type' => 'string', 'notnull' => true));
        $this->hasColumn('level_name', 'string', null, array('type' => 'string', 'notnull' => true));
        $this->hasColumn('level_sys_name', 'string', null, array('type' => 'string', 'notnull' => true));
        $this->hasColumn('optional_level', 'boolean', null, array('type' => 'boolean', 'notnull' => true, 'default' => false));
    }

    public function setUp()
    {
        $this->hasMany('PossibleUpperLevels', array('local' => 'id',
                                                    'foreign' => 'level_upper_ref'));
    }
}