<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMineralogy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mineralogy');
        $this->hasColumn('id', 'integer', null, array('type' => 'integer', 'primary' => true));
        $this->hasColumn('name', 'string', null, array('type' => 'string', 'notnull' => true));
        $this->hasColumn('name_indexed', 'string', null, array('type' => 'string'));
        $this->hasColumn('description_year', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('description_year_compl', 'string', 2, array('type' => 'string', 'length' => '2'));
        $this->hasColumn('level_ref', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('status', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => 'valid'));
        $this->hasColumn('path', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => '/'));
        $this->hasColumn('parent_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('code', 'string', null, array('type' => 'string', 'notnull' => true));
        $this->hasColumn('classification', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => 'strunz'));
        $this->hasColumn('formule', 'string', null, array('type' => 'string'));
        $this->hasColumn('formule_indexed', 'string', null, array('type' => 'string'));
        $this->hasColumn('cristal_system', 'string', null, array('type' => 'string'));
        $this->hasColumn('unit_class_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('unit_class_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('unit_division_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('unit_division_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('unit_family_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('unit_family_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('unit_group_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('unit_group_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('unit_variety_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('unit_variety_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
    }

    public function setUp()
    {
        $this->hasOne('Mineralogy as Parent', array('local' => 'parent_ref',
                                                    'foreign' => 'id'));

        $this->hasMany('Mineralogy', array('local' => 'id',
                                           'foreign' => 'parent_ref'));

        $this->hasMany('Specimens', array('local' => 'id',
                                          'foreign' => 'mineral_ref'));

        $this->hasMany('SpecimensAccompanying', array('local' => 'id',
                                                      'foreign' => 'mineral_ref'));
    }
}