<?php

/**
 * BaseCatalogueLevels
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $level_type
 * @property string $level_name
 * @property string $level_sys_name
 * @property boolean $optional_level
 * @property Doctrine_Collection $PossibleUpperLevels
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class BaseCatalogueLevels extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('catalogue_levels');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('level_type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('level_name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('level_sys_name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('optional_level', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        $this->hasMany('PossibleUpperLevels', array(
             'local' => 'id',
             'foreign' => 'level_upper_ref'));
    }
}