<?php

/**
 * BaseUsersLoginInfos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_ref
 * @property string $login_type
 * @property string $user_name
 * @property string $password
 * @property string $login_system
 * @property string $renew_hash
 * @property string $last_seen
 * @property Users $User
 * 
 * @method integer         getId()           Returns the current record's "id" value
 * @method integer         getUserRef()      Returns the current record's "user_ref" value
 * @method string          getLoginType()    Returns the current record's "login_type" value
 * @method string          getUserName()     Returns the current record's "user_name" value
 * @method string          getPassword()     Returns the current record's "password" value
 * @method string          getLoginSystem()  Returns the current record's "login_system" value
 * @method string          getRenewHash()    Returns the current record's "renew_hash" value
 * @method string          getLastSeen()     Returns the current record's "last_seen" value
 * @method Users           getUser()         Returns the current record's "User" value
 * @method UsersLoginInfos setId()           Sets the current record's "id" value
 * @method UsersLoginInfos setUserRef()      Sets the current record's "user_ref" value
 * @method UsersLoginInfos setLoginType()    Sets the current record's "login_type" value
 * @method UsersLoginInfos setUserName()     Sets the current record's "user_name" value
 * @method UsersLoginInfos setPassword()     Sets the current record's "password" value
 * @method UsersLoginInfos setLoginSystem()  Sets the current record's "login_system" value
 * @method UsersLoginInfos setRenewHash()    Sets the current record's "renew_hash" value
 * @method UsersLoginInfos setLastSeen()     Sets the current record's "last_seen" value
 * @method UsersLoginInfos setUser()         Sets the current record's "User" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsersLoginInfos extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('users_login_infos');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('user_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('login_type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'local',
             ));
        $this->hasColumn('user_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('password', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('login_system', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('renew_hash', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('last_seen', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users as User', array(
             'local' => 'user_ref',
             'foreign' => 'id'));
    }
}
