<?php

/**
 * BaseVernacularNames
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $vernacular_class_ref
 * @property string $name
 * @property string $name_ts
 * @property string $country_language_full_text
 * @property VernacularNames $VernacularNames
 * 
 * @method integer         getVernacularClassRef()         Returns the current record's "vernacular_class_ref" value
 * @method string          getName()                       Returns the current record's "name" value
 * @method string          getNameTs()                     Returns the current record's "name_ts" value
 * @method string          getCountryLanguageFullText()    Returns the current record's "country_language_full_text" value
 * @method VernacularNames getVernacularNames()            Returns the current record's "VernacularNames" value
 * @method VernacularNames setVernacularClassRef()         Sets the current record's "vernacular_class_ref" value
 * @method VernacularNames setName()                       Sets the current record's "name" value
 * @method VernacularNames setNameTs()                     Sets the current record's "name_ts" value
 * @method VernacularNames setCountryLanguageFullText()    Sets the current record's "country_language_full_text" value
 * @method VernacularNames setVernacularNames()            Sets the current record's "VernacularNames" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVernacularNames extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vernacular_names');
        $this->hasColumn('vernacular_class_ref', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('name_ts', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('country_language_full_text', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VernacularNames', array(
             'local' => 'vernacular_class_ref',
             'foreign' => 'id'));
    }
}