<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRecordVisibilities extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('record_visibilities');
        $this->hasColumn('id', 'integer', null, array('type' => 'integer', 'primary' => true, 'autoincrement' => true));
        $this->hasColumn('table_name', 'string', null, array('type' => 'string', 'notnull' => true));
        $this->hasColumn('record_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('db_user_type', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('user_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('visible', 'boolean', null, array('type' => 'boolean', 'notnull' => true, 'default' => true));
    }

    public function setUp()
    {
        $this->hasOne('Users', array('local' => 'user_ref',
                                     'foreign' => 'id'));
    }
}