<?php

/**
 * BaseCollectionsRights
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $collection_ref
 * @property integer $user_ref
 * @property integer $rights
 * @property Collections $Collections
 * @property Users $Users
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
abstract class BaseCollectionsRights extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('collections_rights');
        $this->hasColumn('collection_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('user_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('rights', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Collections', array(
             'local' => 'collection_ref',
             'foreign' => 'id'));

        $this->hasOne('Users', array(
             'local' => 'user_ref',
             'foreign' => 'id'));
    }
}