<?php

/**
 * BaseSpecimenPartsInsurances
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $specimen_part_ref
 * @property integer $insurance_year
 * @property integer $insurance_value
 * @property integer $insurer_ref
 * @property SpecimenParts $SpecimenParts
 * 
 * @method integer                 getSpecimenPartRef()   Returns the current record's "specimen_part_ref" value
 * @method integer                 getInsuranceYear()     Returns the current record's "insurance_year" value
 * @method integer                 getInsuranceValue()    Returns the current record's "insurance_value" value
 * @method integer                 getInsurerRef()        Returns the current record's "insurer_ref" value
 * @method SpecimenParts           getSpecimenParts()     Returns the current record's "SpecimenParts" value
 * @method SpecimenPartsInsurances setSpecimenPartRef()   Sets the current record's "specimen_part_ref" value
 * @method SpecimenPartsInsurances setInsuranceYear()     Sets the current record's "insurance_year" value
 * @method SpecimenPartsInsurances setInsuranceValue()    Sets the current record's "insurance_value" value
 * @method SpecimenPartsInsurances setInsurerRef()        Sets the current record's "insurer_ref" value
 * @method SpecimenPartsInsurances setSpecimenParts()     Sets the current record's "SpecimenParts" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSpecimenPartsInsurances extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('specimen_parts_insurances');
        $this->hasColumn('specimen_part_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('insurance_year', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('insurance_value', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('insurer_ref', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SpecimenParts', array(
             'local' => 'specimen_part_ref',
             'foreign' => 'id'));
    }
}