<?php

/**
 * BaseCollectionsFieldsVisibilities
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $collection_ref
 * @property integer $user_ref
 * @property string $field_group_name
 * @property integer $db_user_type
 * @property boolean $searchable
 * @property boolean $visible
 * @property Collections $Collections
 * @property Users $Users
 * 
 * @method integer                       getCollectionRef()    Returns the current record's "collection_ref" value
 * @method integer                       getUserRef()          Returns the current record's "user_ref" value
 * @method string                        getFieldGroupName()   Returns the current record's "field_group_name" value
 * @method integer                       getDbUserType()       Returns the current record's "db_user_type" value
 * @method boolean                       getSearchable()       Returns the current record's "searchable" value
 * @method boolean                       getVisible()          Returns the current record's "visible" value
 * @method Collections                   getCollections()      Returns the current record's "Collections" value
 * @method Users                         getUsers()            Returns the current record's "Users" value
 * @method CollectionsFieldsVisibilities setCollectionRef()    Sets the current record's "collection_ref" value
 * @method CollectionsFieldsVisibilities setUserRef()          Sets the current record's "user_ref" value
 * @method CollectionsFieldsVisibilities setFieldGroupName()   Sets the current record's "field_group_name" value
 * @method CollectionsFieldsVisibilities setDbUserType()       Sets the current record's "db_user_type" value
 * @method CollectionsFieldsVisibilities setSearchable()       Sets the current record's "searchable" value
 * @method CollectionsFieldsVisibilities setVisible()          Sets the current record's "visible" value
 * @method CollectionsFieldsVisibilities setCollections()      Sets the current record's "Collections" value
 * @method CollectionsFieldsVisibilities setUsers()            Sets the current record's "Users" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BaseCollectionsFieldsVisibilities extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('collections_fields_visibilities');
        $this->hasColumn('collection_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('user_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field_group_name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('db_user_type', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('searchable', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('visible', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Collections', array(
             'local' => 'collection_ref',
             'foreign' => 'id'));

        $this->hasOne('Users', array(
             'local' => 'user_ref',
             'foreign' => 'id'));
    }
}