<?php

/**
 * BaseTagGroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $gtu_ref
 * @property string $group_name
 * @property string $group_name_indexed
 * @property string $sub_group_name
 * @property string $sub_group_name_indexed
 * @property string $group_color
 * @property string $tag_value
 * @property string $tag_value_indexed
 * @property Gtu $Gtu
 * 
 * @method integer   getId()                     Returns the current record's "id" value
 * @method integer   getGtuRef()                 Returns the current record's "gtu_ref" value
 * @method string    getGroupName()              Returns the current record's "group_name" value
 * @method string    getGroupNameIndexed()       Returns the current record's "group_name_indexed" value
 * @method string    getSubGroupName()           Returns the current record's "sub_group_name" value
 * @method string    getSubGroupNameIndexed()    Returns the current record's "sub_group_name_indexed" value
 * @method string    getGroupColor()             Returns the current record's "group_color" value
 * @method string    getTagValue()               Returns the current record's "tag_value" value
 * @method string    getTagValueIndexed()        Returns the current record's "tag_value_indexed" value
 * @method Gtu       getGtu()                    Returns the current record's "Gtu" value
 * @method TagGroups setId()                     Sets the current record's "id" value
 * @method TagGroups setGtuRef()                 Sets the current record's "gtu_ref" value
 * @method TagGroups setGroupName()              Sets the current record's "group_name" value
 * @method TagGroups setGroupNameIndexed()       Sets the current record's "group_name_indexed" value
 * @method TagGroups setSubGroupName()           Sets the current record's "sub_group_name" value
 * @method TagGroups setSubGroupNameIndexed()    Sets the current record's "sub_group_name_indexed" value
 * @method TagGroups setGroupColor()             Sets the current record's "group_color" value
 * @method TagGroups setTagValue()               Sets the current record's "tag_value" value
 * @method TagGroups setTagValueIndexed()        Sets the current record's "tag_value_indexed" value
 * @method TagGroups setGtu()                    Sets the current record's "Gtu" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTagGroups extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag_groups');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('gtu_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('group_name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('group_name_indexed', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('sub_group_name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('sub_group_name_indexed', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('group_color', 'string', null, array(
             'type' => 'string',
             'default' => '#FFFFFF',
             ));
        $this->hasColumn('tag_value', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('tag_value_indexed', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gtu', array(
             'local' => 'gtu_ref',
             'foreign' => 'id'));
    }
}