<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLithostratigraphy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lithostratigraphy');
        $this->hasColumn('id', 'integer', null, array('type' => 'integer', 'primary' => true, 'autoincrement' => true));
        $this->hasColumn('name', 'string', null, array('type' => 'string', 'notnull' => true));
        $this->hasColumn('name_indexed', 'string', null, array('type' => 'string'));
        $this->hasColumn('description_year', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('description_year_compl', 'string', 2, array('type' => 'string', 'length' => '2'));
        $this->hasColumn('level_ref', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('status', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => 'valid'));
        $this->hasColumn('path', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => '/'));
        $this->hasColumn('parent_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('group_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('group_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('formation_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('formation_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('member_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('member_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('layer_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('layer_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('sub_level_1_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('sub_level_1_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('sub_level_2_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('sub_level_2_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
    }

    public function setUp()
    {
        $this->hasOne('Lithostratigraphy as Parent', array('local' => 'parent_ref',
                                                           'foreign' => 'id'));

        $this->hasMany('Lithostratigraphy', array('local' => 'id',
                                                  'foreign' => 'parent_ref'));

        $this->hasMany('Specimens', array('local' => 'id',
                                          'foreign' => 'litho_ref'));
    }
}