<?php

/**
 * BaseGtuTags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tag_group_ref
 * @property integer $gtu_ref
 * @property TagGroups $TagGroups
 * @property Gtu $Gtu
 * 
 * @method integer   getTagGroupRef()   Returns the current record's "tag_group_ref" value
 * @method integer   getGtuRef()        Returns the current record's "gtu_ref" value
 * @method TagGroups getTagGroups()     Returns the current record's "TagGroups" value
 * @method Gtu       getGtu()           Returns the current record's "Gtu" value
 * @method GtuTags   setTagGroupRef()   Sets the current record's "tag_group_ref" value
 * @method GtuTags   setGtuRef()        Sets the current record's "gtu_ref" value
 * @method GtuTags   setTagGroups()     Sets the current record's "TagGroups" value
 * @method GtuTags   setGtu()           Sets the current record's "Gtu" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseGtuTags extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gtu_tags');
        $this->hasColumn('tag_group_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('gtu_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TagGroups', array(
             'local' => 'tag_group_ref',
             'foreign' => 'id'));

        $this->hasOne('Gtu', array(
             'local' => 'gtu_ref',
             'foreign' => 'id'));
    }
}