<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSpecimensAccompanying extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('specimens_accompanying');
        $this->hasColumn('type', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => 'secondary'));
        $this->hasColumn('specimen_ref', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('taxon_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('mineral_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('form', 'string', null, array('type' => 'string'));
        $this->hasColumn('quantity', 'float', null, array('type' => 'float'));
        $this->hasColumn('unit', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => '%'));
    }

    public function setUp()
    {
        $this->hasOne('Specimens', array('local' => 'specimen_ref',
                                         'foreign' => 'id'));

        $this->hasOne('Taxonomy', array('local' => 'taxon_ref',
                                        'foreign' => 'id'));

        $this->hasOne('Mineralogy', array('local' => 'mineral_ref',
                                          'foreign' => 'id'));
    }
}