<?php

/**
 * BasePropertiesValues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $property_ref
 * @property string $property_value
 * @property string $property_value_unified
 * @property float $property_accuracy
 * @property float $property_accuracy_unified
 * @property CatalogueProperties $CatalogueProperties
 * 
 * @method integer             getId()                        Returns the current record's "id" value
 * @method integer             getPropertyRef()               Returns the current record's "property_ref" value
 * @method string              getPropertyValue()             Returns the current record's "property_value" value
 * @method string              getPropertyValueUnified()      Returns the current record's "property_value_unified" value
 * @method float               getPropertyAccuracy()          Returns the current record's "property_accuracy" value
 * @method float               getPropertyAccuracyUnified()   Returns the current record's "property_accuracy_unified" value
 * @method CatalogueProperties getCatalogueProperties()       Returns the current record's "CatalogueProperties" value
 * @method PropertiesValues    setId()                        Sets the current record's "id" value
 * @method PropertiesValues    setPropertyRef()               Sets the current record's "property_ref" value
 * @method PropertiesValues    setPropertyValue()             Sets the current record's "property_value" value
 * @method PropertiesValues    setPropertyValueUnified()      Sets the current record's "property_value_unified" value
 * @method PropertiesValues    setPropertyAccuracy()          Sets the current record's "property_accuracy" value
 * @method PropertiesValues    setPropertyAccuracyUnified()   Sets the current record's "property_accuracy_unified" value
 * @method PropertiesValues    setCatalogueProperties()       Sets the current record's "CatalogueProperties" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePropertiesValues extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('properties_values');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('property_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('property_value', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('property_value_unified', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('property_accuracy', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('property_accuracy_unified', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CatalogueProperties', array(
             'local' => 'property_ref',
             'foreign' => 'id'));
    }
}