<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseIdentifications extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('identifications');
        $this->hasColumn('id', 'integer', null, array('type' => 'integer', 'primary' => true));
        $this->hasColumn('table_name', 'string', null, array('type' => 'string', 'notnull' => true));
        $this->hasColumn('record_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('notion_concerned', 'string', null, array('type' => 'string', 'notnull' => true));
        $this->hasColumn('notion_date', 'timestamp', null, array('type' => 'timestamp'));
        $this->hasColumn('value_defined', 'string', null, array('type' => 'string'));
        $this->hasColumn('value_defined_indexed', 'string', null, array('type' => 'string'));
        $this->hasColumn('value_defined_ts', 'string', null, array('type' => 'string'));
        $this->hasColumn('determination_status', 'string', null, array('type' => 'string'));
        $this->hasColumn('order_by', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => '1'));
    }

}