<?php

/**
 * BasePropertiesValues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $property_ref
 * @property string $property_min
 * @property string $property_min_unified
 * @property string $property_max
 * @property string $property_max_unified
 * @property float $property_accuracy
 * @property float $property_accuracy_unified
 * @property CatalogueProperties $CatalogueProperties
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class BasePropertiesValues extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('properties_values');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('property_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('property_min', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('property_min_unified', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('property_max', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('property_max_unified', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('property_accuracy', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('property_accuracy_unified', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        $this->hasOne('CatalogueProperties', array(
             'local' => 'property_ref',
             'foreign' => 'id'));
    }
}