<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLithology extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lithology');
        $this->hasColumn('id', 'integer', null, array('type' => 'integer', 'primary' => true));
        $this->hasColumn('name', 'string', null, array('type' => 'string', 'notnull' => true));
        $this->hasColumn('name_indexed', 'string', null, array('type' => 'string'));
        $this->hasColumn('description_year', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('description_year_compl', 'string', 2, array('type' => 'string', 'length' => '2'));
        $this->hasColumn('level_ref', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('status', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => 'valid'));
        $this->hasColumn('path', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => '/'));
        $this->hasColumn('parent_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('unit_main_group_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('unit_main_group_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('unit_group_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('unit_group_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('unit_sub_group_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('unit_sub_group_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
        $this->hasColumn('unit_rock_ref', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('unit_rock_indexed', 'string', null, array('type' => 'string', 'notnull' => true, 'default' => ''));
    }

    public function setUp()
    {
        $this->hasOne('Lithology as Parent', array('local' => 'parent_ref',
                                                   'foreign' => 'id'));

        $this->hasMany('Lithology', array('local' => 'id',
                                          'foreign' => 'parent_ref'));

        $this->hasMany('Specimens', array('local' => 'id',
                                          'foreign' => 'lithology_ref'));
    }
}