<?php

/**
 * BaseUsersTrackingRecords
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tracking_ref
 * @property string $field_name
 * @property string $old_value
 * @property string $new_value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class BaseUsersTrackingRecords extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('users_tracking_records');
        $this->hasColumn('tracking_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('field_name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('old_value', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('new_value', 'string', null, array(
             'type' => 'string',
             ));
    }

}