<?php

/**
 * BaseTaxonomy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $name_indexed
 * @property string $name_order_by
 * @property integer $level_ref
 * @property string $status
 * @property string $path
 * @property integer $parent_ref
 * @property boolean $extinct
 * @property Taxonomy $Parent
 * @property CatalogueLevels $Level
 * @property Doctrine_Collection $Taxonomy
 * @property Doctrine_Collection $Specimens
 * @property Doctrine_Collection $SpecimensAccompanying
 * @property Doctrine_Collection $SpecimenSearch
 * @property Doctrine_Collection $IndividualSearch
 * @property Doctrine_Collection $PartSearch
 * @property Doctrine_Collection $IgsSearch
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method string              getNameIndexed()           Returns the current record's "name_indexed" value
 * @method string              getNameOrderBy()           Returns the current record's "name_order_by" value
 * @method integer             getLevelRef()              Returns the current record's "level_ref" value
 * @method string              getStatus()                Returns the current record's "status" value
 * @method string              getPath()                  Returns the current record's "path" value
 * @method integer             getParentRef()             Returns the current record's "parent_ref" value
 * @method boolean             getExtinct()               Returns the current record's "extinct" value
 * @method Taxonomy            getParent()                Returns the current record's "Parent" value
 * @method CatalogueLevels     getLevel()                 Returns the current record's "Level" value
 * @method Doctrine_Collection getTaxonomy()              Returns the current record's "Taxonomy" collection
 * @method Doctrine_Collection getSpecimens()             Returns the current record's "Specimens" collection
 * @method Doctrine_Collection getSpecimensAccompanying() Returns the current record's "SpecimensAccompanying" collection
 * @method Doctrine_Collection getSpecimenSearch()        Returns the current record's "SpecimenSearch" collection
 * @method Doctrine_Collection getIndividualSearch()      Returns the current record's "IndividualSearch" collection
 * @method Doctrine_Collection getPartSearch()            Returns the current record's "PartSearch" collection
 * @method Doctrine_Collection getIgsSearch()             Returns the current record's "IgsSearch" collection
 * @method Taxonomy            setId()                    Sets the current record's "id" value
 * @method Taxonomy            setName()                  Sets the current record's "name" value
 * @method Taxonomy            setNameIndexed()           Sets the current record's "name_indexed" value
 * @method Taxonomy            setNameOrderBy()           Sets the current record's "name_order_by" value
 * @method Taxonomy            setLevelRef()              Sets the current record's "level_ref" value
 * @method Taxonomy            setStatus()                Sets the current record's "status" value
 * @method Taxonomy            setPath()                  Sets the current record's "path" value
 * @method Taxonomy            setParentRef()             Sets the current record's "parent_ref" value
 * @method Taxonomy            setExtinct()               Sets the current record's "extinct" value
 * @method Taxonomy            setParent()                Sets the current record's "Parent" value
 * @method Taxonomy            setLevel()                 Sets the current record's "Level" value
 * @method Taxonomy            setTaxonomy()              Sets the current record's "Taxonomy" collection
 * @method Taxonomy            setSpecimens()             Sets the current record's "Specimens" collection
 * @method Taxonomy            setSpecimensAccompanying() Sets the current record's "SpecimensAccompanying" collection
 * @method Taxonomy            setSpecimenSearch()        Sets the current record's "SpecimenSearch" collection
 * @method Taxonomy            setIndividualSearch()      Sets the current record's "IndividualSearch" collection
 * @method Taxonomy            setPartSearch()            Sets the current record's "PartSearch" collection
 * @method Taxonomy            setIgsSearch()             Sets the current record's "IgsSearch" collection
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaxonomy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomy');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('name_indexed', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('name_order_by', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('level_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'valid',
             ));
        $this->hasColumn('path', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'default' => '/',
             ));
        $this->hasColumn('parent_ref', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('extinct', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Taxonomy as Parent', array(
             'local' => 'parent_ref',
             'foreign' => 'id'));

        $this->hasOne('CatalogueLevels as Level', array(
             'local' => 'level_ref',
             'foreign' => 'id'));

        $this->hasMany('Taxonomy', array(
             'local' => 'id',
             'foreign' => 'parent_ref'));

        $this->hasMany('Specimens', array(
             'local' => 'id',
             'foreign' => 'taxon_ref'));

        $this->hasMany('SpecimensAccompanying', array(
             'local' => 'id',
             'foreign' => 'taxon_ref'));

        $this->hasMany('SpecimenSearch', array(
             'local' => 'id',
             'foreign' => 'taxon_ref'));

        $this->hasMany('IndividualSearch', array(
             'local' => 'id',
             'foreign' => 'taxon_ref'));

        $this->hasMany('PartSearch', array(
             'local' => 'id',
             'foreign' => 'taxon_ref'));

        $this->hasMany('IgsSearch', array(
             'local' => 'id',
             'foreign' => 'taxon_ref'));
    }
}