<?php

/**
 * BaseUsersLanguages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $users_ref
 * @property string $language_country
 * @property boolean $mother
 * @property boolean $prefered_language
 * @property Users $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
abstract class BaseUsersLanguages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('users_languages');
        $this->hasColumn('users_ref', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('language_country', 'string', null, array(
             'type' => 'string',
             'primary' => true,
             ));
        $this->hasColumn('mother', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('prefered_language', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Users as User', array(
             'local' => 'users_ref',
             'foreign' => 'id'));
    }
}