<?php

/**
 * BaseCollections
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property enum $collection_type
 * @property string $code
 * @property string $name
 * @property integer $institution_ref
 * @property integer $main_manager_ref
 * @property integer $parent_ref
 * @property string $path
 * @property boolean $code_auto_increment
 * @property integer $code_last_value
 * @property string $code_prefix
 * @property string $code_prefix_separator
 * @property string $code_suffix
 * @property string $code_suffix_separator
 * @property boolean $code_part_code_auto_copy
 * @property boolean $is_public
 * @property People $Institution
 * @property Users $Manager
 * @property Collections $Parent
 * @property Doctrine_Collection $Collections
 * @property Doctrine_Collection $CollectionsAdmin
 * @property Doctrine_Collection $CollectionsRegUser
 * @property Doctrine_Collection $CollectionsRights
 * @property Doctrine_Collection $Specimens
 * @property Doctrine_Collection $SpecimenSearch
 * @property Doctrine_Collection $IndividualSearch
 * @property Doctrine_Collection $PartSearch
 * 
 * @method integer             getId()                       Returns the current record's "id" value
 * @method enum                getCollectionType()           Returns the current record's "collection_type" value
 * @method string              getCode()                     Returns the current record's "code" value
 * @method string              getName()                     Returns the current record's "name" value
 * @method integer             getInstitutionRef()           Returns the current record's "institution_ref" value
 * @method integer             getMainManagerRef()           Returns the current record's "main_manager_ref" value
 * @method integer             getParentRef()                Returns the current record's "parent_ref" value
 * @method string              getPath()                     Returns the current record's "path" value
 * @method boolean             getCodeAutoIncrement()        Returns the current record's "code_auto_increment" value
 * @method integer             getCodeLastValue()            Returns the current record's "code_last_value" value
 * @method string              getCodePrefix()               Returns the current record's "code_prefix" value
 * @method string              getCodePrefixSeparator()      Returns the current record's "code_prefix_separator" value
 * @method string              getCodeSuffix()               Returns the current record's "code_suffix" value
 * @method string              getCodeSuffixSeparator()      Returns the current record's "code_suffix_separator" value
 * @method boolean             getCodePartCodeAutoCopy()     Returns the current record's "code_part_code_auto_copy" value
 * @method boolean             getIsPublic()                 Returns the current record's "is_public" value
 * @method People              getInstitution()              Returns the current record's "Institution" value
 * @method Users               getManager()                  Returns the current record's "Manager" value
 * @method Collections         getParent()                   Returns the current record's "Parent" value
 * @method Doctrine_Collection getCollections()              Returns the current record's "Collections" collection
 * @method Doctrine_Collection getCollectionsAdmin()         Returns the current record's "CollectionsAdmin" collection
 * @method Doctrine_Collection getCollectionsRegUser()       Returns the current record's "CollectionsRegUser" collection
 * @method Doctrine_Collection getCollectionsRights()        Returns the current record's "CollectionsRights" collection
 * @method Doctrine_Collection getSpecimens()                Returns the current record's "Specimens" collection
 * @method Doctrine_Collection getSpecimenSearch()           Returns the current record's "SpecimenSearch" collection
 * @method Doctrine_Collection getIndividualSearch()         Returns the current record's "IndividualSearch" collection
 * @method Doctrine_Collection getPartSearch()               Returns the current record's "PartSearch" collection
 * @method Collections         setId()                       Sets the current record's "id" value
 * @method Collections         setCollectionType()           Sets the current record's "collection_type" value
 * @method Collections         setCode()                     Sets the current record's "code" value
 * @method Collections         setName()                     Sets the current record's "name" value
 * @method Collections         setInstitutionRef()           Sets the current record's "institution_ref" value
 * @method Collections         setMainManagerRef()           Sets the current record's "main_manager_ref" value
 * @method Collections         setParentRef()                Sets the current record's "parent_ref" value
 * @method Collections         setPath()                     Sets the current record's "path" value
 * @method Collections         setCodeAutoIncrement()        Sets the current record's "code_auto_increment" value
 * @method Collections         setCodeLastValue()            Sets the current record's "code_last_value" value
 * @method Collections         setCodePrefix()               Sets the current record's "code_prefix" value
 * @method Collections         setCodePrefixSeparator()      Sets the current record's "code_prefix_separator" value
 * @method Collections         setCodeSuffix()               Sets the current record's "code_suffix" value
 * @method Collections         setCodeSuffixSeparator()      Sets the current record's "code_suffix_separator" value
 * @method Collections         setCodePartCodeAutoCopy()     Sets the current record's "code_part_code_auto_copy" value
 * @method Collections         setIsPublic()                 Sets the current record's "is_public" value
 * @method Collections         setInstitution()              Sets the current record's "Institution" value
 * @method Collections         setManager()                  Sets the current record's "Manager" value
 * @method Collections         setParent()                   Sets the current record's "Parent" value
 * @method Collections         setCollections()              Sets the current record's "Collections" collection
 * @method Collections         setCollectionsAdmin()         Sets the current record's "CollectionsAdmin" collection
 * @method Collections         setCollectionsRegUser()       Sets the current record's "CollectionsRegUser" collection
 * @method Collections         setCollectionsRights()        Sets the current record's "CollectionsRights" collection
 * @method Collections         setSpecimens()                Sets the current record's "Specimens" collection
 * @method Collections         setSpecimenSearch()           Sets the current record's "SpecimenSearch" collection
 * @method Collections         setIndividualSearch()         Sets the current record's "IndividualSearch" collection
 * @method Collections         setPartSearch()               Sets the current record's "PartSearch" collection
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCollections extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('collections');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('collection_type', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'default' => 'mix',
             'values' => 
             array(
              0 => 'mix',
              1 => 'observation',
              2 => 'physical',
             ),
             ));
        $this->hasColumn('code', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('institution_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('main_manager_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('parent_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('path', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '/',
             ));
        $this->hasColumn('code_auto_increment', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('code_last_value', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('code_prefix', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('code_prefix_separator', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('code_suffix', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('code_suffix_separator', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('code_part_code_auto_copy', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('People as Institution', array(
             'local' => 'institution_ref',
             'foreign' => 'id'));

        $this->hasOne('Users as Manager', array(
             'local' => 'main_manager_ref',
             'foreign' => 'id'));

        $this->hasOne('Collections as Parent', array(
             'local' => 'parent_ref',
             'foreign' => 'id'));

        $this->hasMany('Collections', array(
             'local' => 'id',
             'foreign' => 'parent_ref'));

        $this->hasMany('CollectionsAdmin', array(
             'local' => 'id',
             'foreign' => 'collection_ref'));

        $this->hasMany('CollectionsRegUser', array(
             'local' => 'id',
             'foreign' => 'collection_ref'));

        $this->hasMany('CollectionsRights', array(
             'local' => 'id',
             'foreign' => 'collection_ref'));

        $this->hasMany('Specimens', array(
             'local' => 'id',
             'foreign' => 'collection_ref'));

        $this->hasMany('SpecimenSearch', array(
             'local' => 'id',
             'foreign' => 'collection_ref'));

        $this->hasMany('IndividualSearch', array(
             'local' => 'id',
             'foreign' => 'collection_ref'));

        $this->hasMany('PartSearch', array(
             'local' => 'id',
             'foreign' => 'collection_ref'));
    }
}