<?php

/**
 * BaseVernacularNames
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $vernacular_class_ref
 * @property string $name
 * @property string $name_indexed
 * @property ClassVernacularNames $ClassVernacularNames
 * 
 * @method integer              getId()                   Returns the current record's "id" value
 * @method integer              getVernacularClassRef()   Returns the current record's "vernacular_class_ref" value
 * @method string               getName()                 Returns the current record's "name" value
 * @method string               getNameIndexed()          Returns the current record's "name_indexed" value
 * @method ClassVernacularNames getClassVernacularNames() Returns the current record's "ClassVernacularNames" value
 * @method VernacularNames      setId()                   Sets the current record's "id" value
 * @method VernacularNames      setVernacularClassRef()   Sets the current record's "vernacular_class_ref" value
 * @method VernacularNames      setName()                 Sets the current record's "name" value
 * @method VernacularNames      setNameIndexed()          Sets the current record's "name_indexed" value
 * @method VernacularNames      setClassVernacularNames() Sets the current record's "ClassVernacularNames" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVernacularNames extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vernacular_names');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('vernacular_class_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('name_indexed', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClassVernacularNames', array(
             'local' => 'vernacular_class_ref',
             'foreign' => 'id'));
    }
}