<?php

/**
 * BaseUsersLanguages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $users_ref
 * @property string $language_country
 * @property boolean $mother
 * @property boolean $prefered_language
 * @property Users $User
 * 
 * @method integer        getUsersRef()          Returns the current record's "users_ref" value
 * @method string         getLanguageCountry()   Returns the current record's "language_country" value
 * @method boolean        getMother()            Returns the current record's "mother" value
 * @method boolean        getPreferedLanguage()  Returns the current record's "prefered_language" value
 * @method Users          getUser()              Returns the current record's "User" value
 * @method UsersLanguages setUsersRef()          Sets the current record's "users_ref" value
 * @method UsersLanguages setLanguageCountry()   Sets the current record's "language_country" value
 * @method UsersLanguages setMother()            Sets the current record's "mother" value
 * @method UsersLanguages setPreferedLanguage()  Sets the current record's "prefered_language" value
 * @method UsersLanguages setUser()              Sets the current record's "User" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUsersLanguages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('users_languages');
        $this->hasColumn('users_ref', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('language_country', 'string', null, array(
             'type' => 'string',
             'primary' => true,
             ));
        $this->hasColumn('mother', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('prefered_language', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users as User', array(
             'local' => 'users_ref',
             'foreign' => 'id'));
    }
}