<?php

/**
 * ClassificationKeywords
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
class ClassificationKeywords extends BaseClassificationKeywords
{
  public static function getTags()
  {
    return array(
      'scientific_name_authorship' => 'Scientific Name Authorship',
      'verbatim_taxon_rank' => 'Verbatim Taxon Rank',
      'nomenclatural_status' => 'Nomenclatural Status',
      'specific_epithet' => 'Specific Epithet',
      'infra_specific_epithet' => 'Infra Specific Epithet',
      'uncertainty' => 'Uncertainty',
      'pub_year' => 'Publication Year',
    );
  }
  public static function getTagNameFor($tag)
  {
    $tags = self::getTags();
    return $tags[$tag];
  }
}