<?php

/**
 * ClassificationKeywords
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
class ClassificationKeywords extends BaseClassificationKeywords
{
  public static function getTags($type,$kingdom = null)
  {
    $ts = array(
      'mineral' => array(
        "AuthorTeam", //mineral
        "AuthorTeamAndYear", //mineral     
        "NamedIndividual", // mineral           
      ),
      'botany' => array(
        "GenusOrMonomial",
        "HybridFlag",
        "AuthorTeam",
        "AuthorTeamParenthesis",
        "CultivarGroupName",
        "CultivarName",
        "FirstEpithet",
        "InfraspecificEpithet",
        "TradeDesignationName",
      ),
      'zoology' => array(
        "GenusOrMonomial",
        "Subgenus",
        "SpeciesEpithet",
        "SubspeciesEpithet",
        "AuthorTeamOriginalAndYear",
        "AuthorTeamParenthesisAndYear",
        "CombinationAuthorTeamAndYear",
        "Breed",
      ),
      'bacterology' => array(
        "GenusOrMonomial",
        "Subgenus",
        "SpeciesEpithet",
        "SubspeciesEpithet",
        "ParentheticalAuthorTeamAndYear",
        "NameApprobation",
        "AuthorTeamandYear",
        "SubgenusAuthorandYear",      
      ),
      'virus' => array(
        "GenusOrMonomial",
        "Acronym",
        "ViralSpeciesDesignation",  ///-->
      ),
      'bibliography' => array(
        "address",
        "annote",
        "author",
        "booktitle",
        "chapter",
        "crossref",
        "edition",
        "editor",
        "eprint",
        "howpublished",
        "institution",
        "journal",
        "key",
        "month",
        "note",
        "number",
        "organization",
        "pages",
        "publisher",
        "school",
        "series",
        "title",
        "type",
        "url",
        "volume",
        "year",
      ),
    );
    if($type=='taxonomy' && $kingdom)
    {
      $k_tags = $ts[$kingdom] ;
    }
    elseif($type == 'bibliography') {
      $k_tags = $ts[$type];
    }
    else
      $k_tags = $ts['mineral'] ;

    foreach($k_tags as $t)
    {
        $tags[$t] = sfInflector::humanize( sfInflector::tableize($t));
    }
    return $tags; 
  }
  
  public static function getTagsTitleAndColor($key)
  {
    $ts = array(
        "AuthorTeam" => array('title' => 'The author(s) who published the full name', 'class' => 'Tags_Bota'),
        "AuthorTeamAndYear" => array('title' => 'Author name and year, used in mineralogy or bacterology', 'class' => 'Tags_mix'),
        "AuthorTeamOriginalAndYear" => array('title' => 'The first person(s) who validly published a species', 'class' => 'Tags_Zoo'),
        "AuthorTeamParenthesis" => array('title' => 'Author team of the basionym of a combination', 'class' => 'Tags_Bota'),
        "AuthorTeamParenthesisAndYear" => array('title' => 'The original author when a species was transferred to another genus and the year of the original publication', 'class' => 'Tags_Zoo'),
        "CombinationAuthorTeamAndYear" => array('title' => 'The citation of the authors responsible for the new combination and the year of its publication', 'class' => 'Tags_Zoo'),
        "GenusOrMonomial" => array('title' => 'Genus or higher taxon name, used in each domain', 'class' => 'Tags_mix'),  ///-->
        "HybridFlag" => array('title' => 'Flag indicating that this is a  hybrid ("x") or a  chimaera ("+")', 'class' => 'Tags_Bota'),
        "NameApprobation" => array('title' => 'Valid name', 'class' => 'Tags_Bac'),
        "NamedIndividual" => array('title' => 'Used for cultivated plant name elements', 'class' => 'Tags_Bota'),
        "ParentheticalAuthorTeamAndYear" => array('title' => 'Author team and Year of the basionym of a species or subspecies', 'class' => 'Tags_Bac'),
        "SpeciesEpithet" => array('title' => 'Species name, used in zoology or bacteriology', 'class' => 'Tags_mix'),  ///-->
        "Subgenus" => array('title' => 'Subgenus name, used in zoology or bacteriology', 'class' => 'Tags_mix'),  ///-->
        "SubgenusAuthorAndYear" => array('title' => 'Used to indicate the author and year', 'class' => 'Tags_Bac'),
        "SubspeciesEpithet" => array('title' => 'Subspecies name, used in zoology or bacteriology', 'class' => 'Tags_mix'),  ///-->
        "CultivarGroupName" => array('title' => 'A formal category for cultivars , individual plants or assemblages of plants on the basis of defined similarity', 'class' => 'Tags_Bota'),
        "CultivarName" => array('title' => 'a cultivar name, which is a Latin botanical name followed by an epithet, mostly in a vernacular language', 'class' => 'Tags_Bota'),
        "FirstEpithet" => array('title' => 'species epithet or the epithet of the subdivision of a genus', 'class' => 'Tags_Bota'),  ///-->
        "InfraspecificEpithet" => array('title' => 'The final epithet of a botanical name of infraspecific rank', 'class' => 'Tags_Bota'),  ///-->
        "TradeDesignationName" => array('title' => 'Trade name used for a specific cultivar', 'class' => 'Tags_Bota'), ///Bota
        "Breed" => array('title' => 'Name of the breed of an animal', 'class' => 'Tags_Vir'), ///Tags_Zoo
        "Acronym" => array('title' => 'The accepted acronym for the Virus, e.g. PCV for Peanut Clump Virus', 'class' => 'Tags_Vir'),
        "ViralSpeciesDesignation" => array('title' => 'The formal name of a viral species. Example: Saccharomyces cerevisiae virus L-A', 'class' => 'Tags_Vir'),  ///-->

        "address" => array('title' => 'Publisher\'s address (usually just the city, but can be the full address for lesser-known publishers)', 'class' => 'Tags_mix'),
        "annote" => array('title' => 'An annotation for annotated bibliography styles (not typical)', 'class' => 'Tags_mix'),
        "author" => array('title' => 'The name(s) of the author(s) (in the case of more than one author, separated by and)', 'class' => 'Tags_mix'),
        "booktitle" => array('title' => 'The title of the book, if only part of it is being cited', 'class' => 'Tags_mix'),
        "chapter" => array('title' => 'The chapter number', 'class' => 'Tags_mix'),
        "crossref" => array('title' => 'The key of the cross-referenced entry', 'class' => 'Tags_mix'),
        "edition" => array('title' => 'The edition of a book, long form (such as "first" or "second")', 'class' => 'Tags_mix'),
        "editor" => array('title' => 'The name(s) of the editor(s)', 'class' => 'Tags_mix'),
        "eprint" => array('title' => 'A specification of an electronic publication, often a preprint or a technical report', 'class' => 'Tags_mix'),
        "howpublished" => array('title' => 'How it was published, if the publishing method is nonstandard', 'class' => 'Tags_mix'),
        "institution" => array('title' => 'The institution that was involved in the publishing, but not necessarily the publisher', 'class' => 'Tags_mix'),
        "journal" => array('title' => 'The journal or magazine the work was published in', 'class' => 'Tags_mix'),
        "key" => array('title' => 'A hidden field used for specifying or overriding the alphabetical order of entries (when the "author" and "editor" fields are missing). Note that this is very different from the key (mentioned just after this list) that is used to cite or cross-reference the entry.', 'class' => 'Tags_mix'),
        "month" => array('title' => 'The month of publication (or, if unpublished, the month of creation)', 'class' => 'Tags_mix'),
        "note" => array('title' => 'Miscellaneous extra information', 'class' => 'Tags_mix'),
        "number" => array('title' => 'The "(issue) number" of a journal, magazine, or tech-report, if applicable. (Most publications have a "volume", but no "number" field.)', 'class' => 'Tags_mix'),
        "organization" => array('title' => 'The conference sponsor', 'class' => 'Tags_mix'),
        "pages" => array('title' => ' Page numbers, separated either by commas or double-hyphens.', 'class' => 'Tags_mix'),
        "publisher" => array('title' => 'The publisher\'s name', 'class' => 'Tags_mix'),
        "school" => array('title' => 'The school where the thesis was written', 'class' => 'Tags_mix'),
        "series" => array('title' => 'The series of books the book was published in (e.g. "The Hardy Boys" or "Lecture Notes in Computer Science")', 'class' => 'Tags_mix'),
        "title" => array('title' => 'The title of the work', 'class' => 'Tags_mix'),
        "type" => array('title' => 'The field overriding the default type of publication (e.g. "Research Note" for techreport, "{PhD} dissertation" for phdthesis, "Section" for inbook/incollection)', 'class' => 'Tags_mix'),
        "url" => array('title' => 'The WWW address', 'class' => 'Tags_mix'),
        "volume" => array('title' => 'The volume of a journal or multi-volume book', 'class' => 'Tags_mix'),
        "year" => array('title' => 'The year of publication (or, if unpublished, the year of creation)', 'class' => 'Tags_mix'),

      )  ;
      return($ts[$key]) ;
  }
   
  public function getReadableKeywordType()
  {
    return  sfInflector::humanize( sfInflector::tableize($this->getKeywordType()));
  }

}
