<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollectionsRights extends BaseCollectionsRights
{
	public function deleteCollectionRight()
	{
		$q = Doctrine_Query::create()
		   ->delete('CollectionsRights c')
		   ->where('c.user_ref = ?',$this->getUserRef())
		   ->andWhere('c.collection_ref = ?',$this->getCollectionRef()) ;

		return $q->execute() ;
	}
}
