<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Collections extends BaseCollections
{
  public function getLevel()
  {
      return  substr_count($this->getPath(),'/');
  }
  
  public function __toString()
  {
      return str_repeat('&nbsp;&nbsp;&nbsp;',$this->getLevel()-1).$this->getName();
  }
  public function getNameWithFormat()
  {
    return $this->getName();
  }
  
  public static function getTableByRight($db_user_type)
  {
	  switch ($db_user_type)
	  {
		  case Users::REGISTERED_USER : return 'CollectionsRegUser';
		  case Users::ENCODER : return 'CollectionsRights';
		  case Users::MANAGER : return 'CollectionsAdmin';
		  case Users::ADMIN : return 'CollectionsAdmin';   	  
	  }
  }
}
