<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollectionsTable extends Doctrine_Table
{
    public function fetchByInstitutionList()
    {
        $q = Doctrine_Query::create()
            ->from('People p')
            ->innerJoin('p.Collections col')
            ->select('p.*, col.*, CONCAT(col.path,col.id,E\'/\') as col_path_id')
            ->andWhere('p.is_physical = false')
            ->orderBy('col_path_id ASC');
        return $q->execute();
    }
}