<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollectionMaintenanceTable extends DarwinTable
{
  public function getDistinctActions()
  {
    return $this->createDistinct('CollectionMaintenance', 'action_observation', 'action')->execute();
  }
}