<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentsTable extends DarwinTable
{
  protected static $notions = array('taxonomy' => array('taxon information' => 'taxon information',
                                                        'taxon life history' => 'taxon life history',
                                                       ),
                                    'igs' => array('ig definition' => 'ig definition',
                                                   'diverse' => 'diverse'
                                                  )
                                   );

  /**
  * Find all comments for a table name and a recordId
  * @param string $table_name the table to look for
  * @param int record_id the record to be commented out.
  * @return Doctrine_Collection Collection of Doctrine records
  */
  public function findForTable($table_name, $record_id)
  {
     $q = Doctrine_Query::create()
	 ->from('Comments c')
	 ->andWhere('c.referenced_relation = ?',$table_name)
         ->andWhere('c.record_id = ?',$record_id);
    return $q->execute();
  }
  
  /**
  * Get commentable notions for a given table as an array
  * @param string $table_name The table name
  * @return array an array of key/values with notion that can be commented
  */
  public static function getNotionsFor($table_name)
  {
    return self::$notions[$table_name];
  }
}