<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Comments extends BaseComments
{
  public function getNotionText()
  {
    $notions = CommentsTable::getNotionsFor($this->get('referenced_relation'));
    return $notions[$this->getNotionConcerned()];
  }

  public function getLink()
  {
    return $this->getTable()->getLinkforKnownTable($this->getReferencedRelation(),$this->getRecordId());
  }
}
