<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Expeditions extends BaseExpeditions
{
  public function getExpeditionFromDateMasked ()
  {
    $dateTime = new FuzzyDateTime($this->_get('expedition_from_date'), $this->_get('expedition_from_date_mask'));
    return $dateTime->getDateMasked();
  }
  
  public function getExpeditionToDateMasked ()
  {
    $dateTime = new FuzzyDateTime($this->_get('expedition_to_date'), $this->_get('expedition_to_date_mask'));
    return $dateTime->getDateMasked();
  }
  
  public function getExpeditionFromDate()
  {
    $from_date = new FuzzyDateTime($this->_get('expedition_from_date'), $this->_get('expedition_from_date_mask'));
    return $from_date->getDateTimeMaskedAsArray();
  }

  public function getExpeditionToDate()
  {
    $to_date = new FuzzyDateTime($this->_get('expedition_to_date'), $this->_get('expedition_to_date_mask'), false);
    return $to_date->getDateTimeMaskedAsArray();
  }

  public function setExpeditionFromDate($fd)
  {
    if ($fd instanceof FuzzyDateTime)
    {
      $this->_set('expedition_from_date', $fd->format('Y/m/d'));
      $this->_set('expedition_from_date_mask', $fd->getMask());
    }
    else
    {
      $dateTime = new FuzzyDateTime($fd, 56, true); 
      $this->_set('expedition_from_date', $dateTime->format('Y/m/d'));
      $this->_set('expedition_from_date_mask', $dateTime->getMask());
    }
  }

  public function setExpeditionToDate($fd)
  {
    if ($fd instanceof FuzzyDateTime)
    {
      $this->_set('expedition_to_date', $fd->format('Y/m/d'));
      $this->_set('expedition_to_date_mask', $fd->getMask());
    }
    else
    {
      $dateTime = new FuzzyDateTime($fd, 56, false); 
      $this->_set('expedition_to_date', $dateTime->format('Y/m/d'));
      $this->_set('expedition_to_date_mask', $dateTime->getMask());
    }
  }

  public function getName()
  {
    if(! $this->isNew() && $this->_get('id')==0)
      return '-';
    return $this->_get('name');
  }

}
