<?php

/**
 * FlatDict
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FlatDict extends BaseFlatDict
{
 public function getTypeFormated()
  {
    return ucfirst($this->_get('type'));
  }

  public function getTypeSearchFormated()
  {
    return ucfirst($this->_get('type_search'));
  }

  public function getTypeGroupFormated()
  {
    return ucfirst($this->_get('type_group'));
  }

  public function getSexFormated()
  {
    if ($this->_get('sex') == 'undefined')
      return '-';
    return ucfirst($this->_get('sex'));
  }

  public function getSexSearchFormated()
  {
    return ucfirst($this->_get('sex'));
  }

  public function getStateFormated()
  {
    if ($this->_get('state') == 'not applicable')
      return '-';
    return ucfirst($this->_get('state'));
  }

  public function getStateSearchFormated()
  {
    return ucfirst($this->_get('state'));
  }

  public function getStageFormated()
  {
    if ($this->_get('stage') == 'undefined')
      return '-';
    return ucfirst($this->_get('stage'));
  }

  public function getStageSearchFormated()
  {
    return ucfirst($this->_get('stage'));
  }

  public function getSocialStatusFormated()
  {
    if ($this->_get('social_status') == 'not applicable')
      return '-';
    return ucfirst($this->_get('social_status'));
  }

  public function getSocialStatusSearchFormated()
  {
    return ucfirst($this->_get('social_status'));
  }

  public function getRockFormFormated()
  {
    if ($this->_get('rock_form') == 'not applicable')
      return '-';
    return ucfirst($this->_get('rock_form'));
  }

  public function getRockFormSearchFormated()
  {
    return ucfirst($this->_get('rock_form'));
  }

}
