<?php

/**
 * Institution
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Institutions extends BaseInstitutions
{
  public function __toString()
  {
        return $this->getFormatedName();
  }

  public static function getTypes()
  {
    return array(
      8 => 'Expert',
    );
  }

  public function getDbPeopleType()
  {
    $result = array();
    foreach(self::getTypes() as $k => $value)
    {
      if($k & $this->_get('db_people_type'))
      {
	$result[] = $k;
      }
    }
    return $result;
  }

  public function setDbPeopleType($db_types)
  {
    $result = 0;
    $types = self::getTypes();
    if(is_array($db_types))
    {
      foreach($db_types as $value)
      {
	if(isset($types[$value]))
	  $result += $value;
      }
      $this->_set('db_people_type', $result);
    }
    else
      $this->_set('db_people_type', $db_types);

  }

}
