<?php

/**
 * LoanItemsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoanItemsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoanItemsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LoanItems');
    }
}