<?php

/**
 * LoansTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoansTable extends DarwinTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoansTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Loans');
    }
}