<?php

/**
 * LoanStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoanStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoanStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LoanStatus');
    }
}