<?php

/**
 * PartSearch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PartSearch extends BasePartSearch
{
    public function getCountryTags()
    {
      $tags = explode(';',$this->getGtuCountryTagValue(''));
      $nbr = count($tags);
      if(! $nbr) return "-";
      $str = '<ul class="name_tags">';
      foreach($tags as $value)
        if (strlen($value))
          $str .=  '<li>' . trim($value).'</li>';
      $str .= '</ul>';
      
      return $str;
    }

    public function getOtherGtuTags()
    {
      $tags = explode(';',$this->getGtuCountryTagValue(''));
      $nbr = count($tags);
      if(! $nbr) return "-";
      $str = '<ul class="name_tags">';
      foreach($tags as $value)
        if (strlen($value))
          $str .=  '<li>' . trim($value).'</li>';
      $str .= '</ul>';
      
      return $str;
    }

  /* Function returning a flag telling if for the current specimen there are types or not */
  public function getWithTypes()
  {
    if($this->getIndividualType() != 'specimen') return true;
    else return false;
  }

  public function getAggregatedName($sep = ' / ')
  {
    $items = array(
        $this->getCollectionName(),
        $this->getTaxonName(),
        $this->getIndividualTypeGroup(),
        $this->getIndividualSex(),
        $this->getBuilding(),
        $this->getFloor(),
        $this->getRoom(),
        $this->getRow(),
        $this->getShelf(),
      );
    $items = array_filter($items);
    return implode($sep, $items);
  }
}
