<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeopleTable extends Doctrine_Table
{
  /**
  * Search all physical people by name
  * @param string $name a part of the formated name to look for (with ts)
  * @return Doctrine_Collection Collection of People
  */
  public function searchPysical($name)
  {
    $q = Doctrine_Query::create()
	 ->from('People p')
	->andWhere('p.is_physical = ?', true)
	->andWhere('p.formated_name_ts @@ to_tsquery(\'simple\',?)',$name);
    return $q->execute();
  }
}