<?php

/**
 * SpecimensFlatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpecimensFlatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpecimensFlatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SpecimensFlat');
    }
}