<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpecimenParts extends BaseSpecimenParts
{
  public static function getCategories()
  {
	return array(
	  'physical' => 'Physical',
	  'observation' => 'observation',
	  'figurate' => 'figurate',
	);
  }
  
  public function getName()
  {
	return $this->_get('id');
  }

  public function getLevel()
  {
    return  substr_count($this->getPath(),'/');
  }
    
  public function getSpacing()
  {
    return str_repeat('&nbsp;&nbsp;&nbsp;',$this->getLevel()-1);
  }
}