<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpecimenParts extends BaseSpecimenParts
{
  public static function getCategories()
  {
    return array(
      'physical' => 'Physical',
      'observation' => 'Observation',
      'figurate' => 'Figurate',
    );
  }

  public function getName()
  {
    $code_name = "" ;
    $codes = Doctrine::getTable('Codes')->getCodesRelated('specimen_parts', $this->getId()) ;
    foreach($codes as $code)
    {
      $code_name = $code->getCodePrefix().$code->getCodePrefixSeparator().$code->getCode().$code->getCodeSuffixSeparator().$code->getCodeSuffix()." - " ;
      break;
    }
    return $code_name.$this->getSpecimenPart();
  }

  public function getLevel()
  {
    return  substr_count($this->getPath(),'/');
  }
    
  public function getSpacing()
  {
    return str_repeat('&nbsp;&nbsp;&nbsp;',$this->getLevel()-1);
  }
}
