<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpecimensTable extends DarwinTable
{
    static public $acquisition_category = array(
        'Undefined' => 'Undefined',
        'Donation' => 'Donation',
        'Exchange' => 'Exchange',
        'Internal work' => 'Internal work',
        'Loan' => 'Loan',
        'Mission' => 'Mission',
        'Purchase' => 'Purchase',
        'seizure' => 'Judicial seizure',
        'Trip' => 'Trip',
        'Excavation' => 'Excavation',
        'Exploration' => 'Exploration',
        'Collect' => 'Collect',
        );

    /**
    * Get differents acquisition categories
    * @return array of key/value of acquisition categories
    */
    public static function getDistinctCategories()
    {
        try{
            $i18n_object = sfContext::getInstance()->getI18n();
        }
        catch( Exception $e )
        {
            return self::$acquisition_category;
        }
        return array_map(array($i18n_object, '__'), self::$acquisition_category);
    }

    /**
    * Get distinct tools
    * @return Doctrine_collection with distinct "tool" as column
    */
    public function getDistinctTools()
    {
      return $this->createDistinct('Specimens', 'collecting_tool', 'tool')->execute();
    }

    /**
    * Get distinct Method
    * @return Doctrine_collection with distinct "method" as column
    */
    public function getDistinctMethods()
    {
	return $this->createDistinct('Specimens', 'collecting_method', 'method')->execute();
    }

    /**
    * Get distinct Host Relationships
    * @return Doctrine_collection with distinct "host_relationship" as column
    */
    public function getDistinctHostRelationships()
    {
	return $this->createDistinct('Specimens', 'host_relationship', 'host_relationship')->execute();
    }
    
    public function getSpecimenByRef($collection_id,$taxon_id)
    {
	   $q = Doctrine_Query::create()
		->from('specimens s')
		->where('s.collection_ref = ?', $collection_id)
		->andWhere('s.taxon_ref = ?', $taxon_id);

	   return $q->fetchOne(); 
    }

}
