<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpecimensAccompanyingTable extends DarwinTable
{
  /**
  * Get Distincts Forms
  * @return array an Array of forms in keys
  */
  public function getDistinctForms()
  {
    return $this->createFlatDistinct('specimens_accompanying', 'form', 'form')->execute();
  }
  
  public function findBySpecimen($spec_id)
  {
    $q = Doctrine_Query::create()->
         from('SpecimensAccompanying')->
         where('specimen_ref = ?', $spec_id);
    return $q->execute();  
  }
}
