<?php

/**
 * StagingInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StagingInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StagingInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StagingInfo');
    }
}
