<?php

/**
 * StagingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StagingTable extends DarwinTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object StagingTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Staging');
  }
  
  /**
  * Get distinct Host Relationships
  * @return Doctrine_collection with distinct "host_relationship" as column
  */
  public function getDistinctHostRelationships()
  {
      return $this->createFlatDistinct('specimens', 'host_relationship', 'host_relationship')->execute();
  }    
}
