<?php

/**
 * StagingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StagingTable extends DarwinTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object StagingTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Staging');
  }
  
  /**
  * Get distinct Host Relationships
  * @return Doctrine_collection with distinct "host_relationship" as column
  */
  public function getDistinctHostRelationships()
  {
      return $this->createFlatDistinct('specimens', 'host_relationship', 'host_relationship')->execute();
  }

  public function findLinked($record_ids)
  {
    if(! count($record_ids)) return array();
    $conn = Doctrine_Manager::connection();
    $sql = "select record_id, count(*) as cnt FROM template_table_record_ref r where referenced_relation='staging' and 
      record_id in (".implode(',',$record_ids).") GROUP BY record_id";
    $result = $conn->fetchAssoc($sql);
    return $result;
  }

  public function markTaxon($import_ref)
  {
    $q = Doctrine_Query::create()
      ->update('Staging')
      ->set('create_taxon', '?','true')
      ->andwhere('import_ref = ? ',$import_ref)
      ->execute();
    $q = Doctrine_Query::create()->update('Imports');
    $q->andwhere('id = ? ',$import_ref)
      ->set('state', '?','processing')
      ->execute();
  }
}
