<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxonomyTable extends DarwinTable
{

  public function getTaxonByName($name,$level,$path)
  {
    $q = Doctrine_Query::create()
      ->from('Taxonomy t')
      ->where('t.name = ?', $name)
      ->andWhere('t.level_ref = ?', $level)
      ->andWhere('t.path = ?', $path);

    return $q->fetchOne();
  }

  public function getRealTaxon()
  {
    $q = Doctrine_Query::create()
      ->from('Taxonomy t')
      ->where('t.id > 0') ;
      return $q->execute() ;
  }

  public function getLevelTaxonParent($parents)
  {
    $catalogue_level =array();
    if(count($parents) == 0) return $catalogue_level ;
    $q= Doctrine_Query::create()
      ->from('CatalogueLevels cl')
      ->orderby('level_order')
      ->wherein('level_sys_name',array_keys($parents)) ;
    $result = $q->execute() ;
    foreach ($result as $catalogue) {
      $q = Doctrine_Query::create()
        ->from('Taxonomy t')
        ->innerjoin('t.Level l')
        ->where('t.name_indexed ilike fulltoindex(?) || \'%\' ', $parents[$catalogue->getLevelSysName()])
        ->andWhere('l.level_sys_name = ?', $catalogue->getLevelSysName());
      $taxon = $q->fetchOne();
      $catalogue_level[$catalogue->getLevelName()] = array(
        'name' => $parents[$catalogue->getLevelSysName()],
        'level_ref' => $catalogue->getId(),
        'class' => $taxon? $taxon->getId(): '') ;
    }
    return($catalogue_level) ;
  }
}
