<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersComm extends BaseUsersComm
{
  private static $comm_type = array('phone/fax'=> 'phone/fax', 'e-mail' => 'e-mail');
  /**
  * Get list of communication types available
  * @return array Array of list of communication types
  */
  public static function getCommTypes()
  {
    try{
        $i18n_object = sfContext::getInstance()->getI18n();
    }
    catch( Exception $e )
    {
        return self::$comm_type;
    }
    return array_map(array($i18n_object, '__'), self::$comm_type);
  }

  /**
  * Get the communication types available for registering
  * @return string Give the comm type available for registering
  */
  public static function getRegisterCommType()
  {
    return 'e-mail';
  }

  /**
  * Get tags of the comm as an array (only label not keys)
  * @return array Array of tags for this comm
  */
  public function getTagsAsArray()
  {
    $array = explode(',',$this->_get('tag'));
    $result = array();
    $possible_tags = Doctrine::getTable('UsersComm')->getTags($this->_get('comm_type'));
    foreach($array as $tag)
    {
      $tag=trim($tag);
      if(isset($possible_tags[$tag]))
        $result[] = $possible_tags[$tag];
    }
    return $result;
  }
  
  public function getDisplayImage($domain = 'all')
  {
    if (strstr($this->getTag(),'work') || $domain == 'all')
    {
      if($this->getCommType() == "e-mail") return "email.png";      
      elseif (strstr($this->getTag(),'fax'))
        return "fax.png" ;
      else
        return "tel.png" ;
    }  
  }
}
