<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersTracking extends BaseUsersTracking
{
  public function getLink()
  {
    $result = $this->getLinkforKnownTable($this->_get('referenced_relation') , $this->_get('record_id'));
    if($result)
      return $result;
    $result = $this->getLinkforRefTable($this->_get('referenced_relation') , $this->_get('record_id'));
    if($result)
      return $result;
    return "";
  }
  
  protected function getLinkforKnownTable($table, $id)
  {
    switch($table)
    {
      case 'collections':
        $link = 'collection/edit?id='.$id; break;
      case 'specimens':
        $link = 'specimen/edit?id='.$id; break;
      case 'specimen_individuals':
        $link = 'individuals/edit?id='.$id; break;
      case 'specimen_parts':
        $link = 'parts/edit?id='.$id; break;
      case 'expeditions':
        $link = 'expedition/edit?id='.$id; break;
      case 'taxonomy':
      case 'lithology':
      case 'lithostratigraphy':
      case 'chronostratigraphy':
      case 'mineralogy':
      case 'people':
      case 'insurances':
      case 'igs':
      case 'gtu':
        $link = $table.'/edit?id='.$id; break;
      default:
        $link = false; break;
    }
    return $link;
  }

  protected function getLinkforRefTable($table, $id)
  {
    $hstore = $this->_get('new_value');
    eval("\$hvals = array({$hstore});");
    if(isset($hvals['referenced_relation']) && isset($hvals['record_id']))
      return $this->getLinkforKnownTable($hvals['referenced_relation'],$hvals['record_id']);

    if(isset($hvals['referenced_relation']) && isset($hvals['record_id_1']))
      return $this->getLinkforKnownTable($hvals['referenced_relation'],$hvals['record_id_1']);

    if($table == 'collections_rights')
      return $this->getLinkforKnownTable('collections',$hvals['collection_ref']);

    if($table == 'tag_groups')
      return $this->getLinkforKnownTable('gtu',$hvals['gtu_ref']);

    if($table == 'specimen_collecting_methods' || $table == 'specimen_collecting_tools')
      return $this->getLinkforKnownTable('specimens',$hvals['specimen_ref']);

    return false;
  }

  /** When using the form filter **/
  public function getDiffAsArray($is_old = true)
  {
    if($is_old)
      $hstore = $this->_get('old_value');
    else
      $hstore = $this->_get('new_value');
    eval("\$diff = array({$hstore});");
    foreach($diff as $key=>$value)
    {
      if(preg_match("/_indexed$/", $key) || preg_match("/_name_ts$/", $key) || preg_match("/_order_by$/", $key))
        unset($diff[$key]);
    }
    return $diff;
  }
}

