<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Users extends BaseUsers
{
    public function __toString()
    {
        return $this->getFormatedName();
    }
    
    //function getStatus, return a 'title' for a user : 'M' for a Male, 'F' for a female, and 'moral' for a non physical user
    public function getStatus()
    {
       $gender = $this->getGender()  ;
       if (!$this->getIsPhysical())
       	return ("moral") ;
       else 
       	return (strtolower($gender)) ;
    }
    
    public static function getTypes($options)
    {
    	if (isset($options['screen']) && $options['screen'] == 1) return array(4=>Users::getTypeName(4)) ;
     $db_user_type = array(
      1 => Users::getTypeName(1),
      2 => Users::getTypeName(2),
      4 => Users::getTypeName(4),
      8 => Users::getTypeName(8)
      );
      if ($options['db_user_type'] != 8) { 
      	array_pop($db_user_type) ;
	     array_pop($db_user_type) ;
	 }
	 return $db_user_type ;
    }
    
    public static function getTypeName($db_user_type)
    {
    	  switch ($db_user_type) {
    	  	case 1 : return 'Registered user';
    	  	case 2 : return 'Encoder';
    	  	case 4 : return 'Collection manager';
          case 8 : return 'Administrator';   	  
    	  }
    
    }
    // function to add all user's widgets in my_preference table
    public static function addUserWidgets($user_id)
    {
	  $count_widget = 0;
	  $array_right = Users::getTypes(array('db_user_type' => 8)) ;
	  foreach ($array_right as $key => $right)
	  {
		  $file = MyPreferences::getFileByRight($right) ;
		  if($file)
		  {
			  $data = new Doctrine_Parser_Yml;
			  $array = $data->loadData($file);
			  foreach ($array as $widget => $array_values) {
				$pref = new MyPreferences() ;
				$pref->addWidget($array_values, $user_id) ;
				$count_widget++;
			  }
		  }
	  }
	  return $count_widget;
    }
}
