<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Users extends BaseUsers
{
    public function __toString()
    {
        return $this->getFormatedName();
    }
    public static function getTypes()
    {
     return array(
      1 => 'Registered user',
      2 => 'Encoder',
      4 => 'Collection manager',
      );
    }
}
