<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersCommTable extends DarwinTable
{
  public function getTags($type)
  {
    if($type=="TEL")
      return array('home'=>'Home', 'pager'=>'Pager', 'work'=>'Work', 'pref'=>'Preferred', 'voice'=>'Voice', 'fax'=>'Fax', 'cell'=>'Cell');
    else
      return array('home'=>'Home','pref'=>'Preferred', 'work'=>'Work','internet'=> 'Internet');
  }

  public function fetchByUser($id)
  {
    $q = Doctrine_Query::create()
	  ->from('UsersComm r')
	  ->where('r.person_user_ref = ?',$id)
	  ->orderBy('r.comm_type ASC, r.id ASC');
    return $q->execute();
  }
}