<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersLoginInfos extends BaseUsersLoginInfos
{
  protected function addLoginInfo($user)
  {
     $this->loadDataFromArray($user)->save();
  }
  
  public function setNewPassword($values)
  {
    if($values) $this->setPassword(sha1(sfConfig::get('dw_salt').$values))  ;
  }
}
