<?php

/**
 * Taxonomy form base class.
 *
 * @method Taxonomy getObject() Returns the current form's model object
 *
 * @package    darwin
 * @subpackage form
 * @author     DB team <collections@naturalsciences.be>
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 24051 2009-11-16 21:08:08Z Kris.Wallsmith $
 */
abstract class BaseTaxonomyForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id'                           => new sfWidgetFormInputHidden(),
      'name'                         => new sfWidgetFormTextarea(),
      'name_indexed'                 => new sfWidgetFormTextarea(),
      'level_ref'                    => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Level'), 'add_empty' => true)),
      'status'                       => new sfWidgetFormTextarea(),
      'path'                         => new sfWidgetFormTextarea(),
      'parent_ref'                   => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Parent'), 'add_empty' => true)),
      'domain_ref'                   => new sfWidgetFormInputText(),
      'domain_indexed'               => new sfWidgetFormTextarea(),
      'kingdom_ref'                  => new sfWidgetFormInputText(),
      'kingdom_indexed'              => new sfWidgetFormTextarea(),
      'super_phylum_ref'             => new sfWidgetFormInputText(),
      'super_phylum_indexed'         => new sfWidgetFormTextarea(),
      'phylum_ref'                   => new sfWidgetFormInputText(),
      'phylum_indexed'               => new sfWidgetFormTextarea(),
      'sub_phylum_ref'               => new sfWidgetFormInputText(),
      'sub_phylum_indexed'           => new sfWidgetFormTextarea(),
      'infra_phylum_ref'             => new sfWidgetFormInputText(),
      'infra_phylum_indexed'         => new sfWidgetFormTextarea(),
      'super_cohort_botany_ref'      => new sfWidgetFormInputText(),
      'super_cohort_botany_indexed'  => new sfWidgetFormTextarea(),
      'cohort_botany_ref'            => new sfWidgetFormInputText(),
      'cohort_botany_indexed'        => new sfWidgetFormTextarea(),
      'sub_cohort_botany_ref'        => new sfWidgetFormInputText(),
      'sub_cohort_botany_indexed'    => new sfWidgetFormTextarea(),
      'infra_cohort_botany_ref'      => new sfWidgetFormInputText(),
      'infra_cohort_botany_indexed'  => new sfWidgetFormTextarea(),
      'super_class_ref'              => new sfWidgetFormInputText(),
      'super_class_indexed'          => new sfWidgetFormTextarea(),
      'class_ref'                    => new sfWidgetFormInputText(),
      'class_indexed'                => new sfWidgetFormTextarea(),
      'sub_class_ref'                => new sfWidgetFormInputText(),
      'sub_class_indexed'            => new sfWidgetFormTextarea(),
      'infra_class_ref'              => new sfWidgetFormInputText(),
      'infra_class_indexed'          => new sfWidgetFormTextarea(),
      'super_division_ref'           => new sfWidgetFormInputText(),
      'super_division_indexed'       => new sfWidgetFormTextarea(),
      'division_ref'                 => new sfWidgetFormInputText(),
      'division_indexed'             => new sfWidgetFormTextarea(),
      'sub_division_ref'             => new sfWidgetFormInputText(),
      'sub_division_indexed'         => new sfWidgetFormTextarea(),
      'infra_division_ref'           => new sfWidgetFormInputText(),
      'infra_division_indexed'       => new sfWidgetFormTextarea(),
      'super_legion_ref'             => new sfWidgetFormInputText(),
      'super_legion_indexed'         => new sfWidgetFormTextarea(),
      'legion_ref'                   => new sfWidgetFormInputText(),
      'legion_indexed'               => new sfWidgetFormTextarea(),
      'sub_legion_ref'               => new sfWidgetFormInputText(),
      'sub_legion_indexed'           => new sfWidgetFormTextarea(),
      'infra_legion_ref'             => new sfWidgetFormInputText(),
      'infra_legion_indexed'         => new sfWidgetFormTextarea(),
      'super_cohort_zoology_ref'     => new sfWidgetFormInputText(),
      'super_cohort_zoology_indexed' => new sfWidgetFormTextarea(),
      'cohort_zoology_ref'           => new sfWidgetFormInputText(),
      'cohort_zoology_indexed'       => new sfWidgetFormTextarea(),
      'sub_cohort_zoology_ref'       => new sfWidgetFormInputText(),
      'sub_cohort_zoology_indexed'   => new sfWidgetFormTextarea(),
      'infra_cohort_zoology_ref'     => new sfWidgetFormInputText(),
      'infra_cohort_zoology_indexed' => new sfWidgetFormTextarea(),
      'super_order_ref'              => new sfWidgetFormInputText(),
      'super_order_indexed'          => new sfWidgetFormTextarea(),
      'order_ref'                    => new sfWidgetFormInputText(),
      'order_indexed'                => new sfWidgetFormTextarea(),
      'sub_order_ref'                => new sfWidgetFormInputText(),
      'sub_order_indexed'            => new sfWidgetFormTextarea(),
      'infra_order_ref'              => new sfWidgetFormInputText(),
      'infra_order_indexed'          => new sfWidgetFormTextarea(),
      'section_zoology_ref'          => new sfWidgetFormInputText(),
      'section_zoology_indexed'      => new sfWidgetFormTextarea(),
      'sub_section_zoology_ref'      => new sfWidgetFormInputText(),
      'sub_section_zoology_indexed'  => new sfWidgetFormTextarea(),
      'super_family_ref'             => new sfWidgetFormInputText(),
      'super_family_indexed'         => new sfWidgetFormTextarea(),
      'family_ref'                   => new sfWidgetFormInputText(),
      'family_indexed'               => new sfWidgetFormTextarea(),
      'sub_family_ref'               => new sfWidgetFormInputText(),
      'sub_family_indexed'           => new sfWidgetFormTextarea(),
      'infra_family_ref'             => new sfWidgetFormInputText(),
      'infra_family_indexed'         => new sfWidgetFormTextarea(),
      'super_tribe_ref'              => new sfWidgetFormInputText(),
      'super_tribe_indexed'          => new sfWidgetFormTextarea(),
      'tribe_ref'                    => new sfWidgetFormInputText(),
      'tribe_indexed'                => new sfWidgetFormTextarea(),
      'sub_tribe_ref'                => new sfWidgetFormInputText(),
      'sub_tribe_indexed'            => new sfWidgetFormTextarea(),
      'infra_tribe_ref'              => new sfWidgetFormInputText(),
      'infra_tribe_indexed'          => new sfWidgetFormTextarea(),
      'genus_ref'                    => new sfWidgetFormInputText(),
      'genus_indexed'                => new sfWidgetFormTextarea(),
      'sub_genus_ref'                => new sfWidgetFormInputText(),
      'sub_genus_indexed'            => new sfWidgetFormTextarea(),
      'section_botany_ref'           => new sfWidgetFormInputText(),
      'section_botany_indexed'       => new sfWidgetFormTextarea(),
      'sub_section_botany_ref'       => new sfWidgetFormInputText(),
      'sub_section_botany_indexed'   => new sfWidgetFormTextarea(),
      'serie_ref'                    => new sfWidgetFormInputText(),
      'serie_indexed'                => new sfWidgetFormTextarea(),
      'sub_serie_ref'                => new sfWidgetFormInputText(),
      'sub_serie_indexed'            => new sfWidgetFormTextarea(),
      'super_species_ref'            => new sfWidgetFormInputText(),
      'super_species_indexed'        => new sfWidgetFormTextarea(),
      'species_ref'                  => new sfWidgetFormInputText(),
      'species_indexed'              => new sfWidgetFormTextarea(),
      'sub_species_ref'              => new sfWidgetFormInputText(),
      'sub_species_indexed'          => new sfWidgetFormTextarea(),
      'variety_ref'                  => new sfWidgetFormInputText(),
      'variety_indexed'              => new sfWidgetFormTextarea(),
      'sub_variety_ref'              => new sfWidgetFormInputText(),
      'sub_variety_indexed'          => new sfWidgetFormTextarea(),
      'form_ref'                     => new sfWidgetFormInputText(),
      'form_indexed'                 => new sfWidgetFormTextarea(),
      'sub_form_ref'                 => new sfWidgetFormInputText(),
      'sub_form_indexed'             => new sfWidgetFormTextarea(),
      'abberans_ref'                 => new sfWidgetFormInputText(),
      'abberans_indexed'             => new sfWidgetFormTextarea(),
      'extinct'                      => new sfWidgetFormInputCheckbox(),
    ));

    $this->setValidators(array(
      'id'                           => new sfValidatorDoctrineChoice(array('model' => $this->getModelName(), 'column' => 'id', 'required' => false)),
      'name'                         => new sfValidatorString(),
      'name_indexed'                 => new sfValidatorString(array('required' => false)),
      'level_ref'                    => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Level'), 'required' => false)),
      'status'                       => new sfValidatorString(array('required' => false)),
      'path'                         => new sfValidatorString(array('required' => false)),
      'parent_ref'                   => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Parent'), 'required' => false)),
      'domain_ref'                   => new sfValidatorInteger(array('required' => false)),
      'domain_indexed'               => new sfValidatorString(array('required' => false)),
      'kingdom_ref'                  => new sfValidatorInteger(array('required' => false)),
      'kingdom_indexed'              => new sfValidatorString(array('required' => false)),
      'super_phylum_ref'             => new sfValidatorInteger(array('required' => false)),
      'super_phylum_indexed'         => new sfValidatorString(array('required' => false)),
      'phylum_ref'                   => new sfValidatorInteger(array('required' => false)),
      'phylum_indexed'               => new sfValidatorString(array('required' => false)),
      'sub_phylum_ref'               => new sfValidatorInteger(array('required' => false)),
      'sub_phylum_indexed'           => new sfValidatorString(array('required' => false)),
      'infra_phylum_ref'             => new sfValidatorInteger(array('required' => false)),
      'infra_phylum_indexed'         => new sfValidatorString(array('required' => false)),
      'super_cohort_botany_ref'      => new sfValidatorInteger(array('required' => false)),
      'super_cohort_botany_indexed'  => new sfValidatorString(array('required' => false)),
      'cohort_botany_ref'            => new sfValidatorInteger(array('required' => false)),
      'cohort_botany_indexed'        => new sfValidatorString(array('required' => false)),
      'sub_cohort_botany_ref'        => new sfValidatorInteger(array('required' => false)),
      'sub_cohort_botany_indexed'    => new sfValidatorString(array('required' => false)),
      'infra_cohort_botany_ref'      => new sfValidatorInteger(array('required' => false)),
      'infra_cohort_botany_indexed'  => new sfValidatorString(array('required' => false)),
      'super_class_ref'              => new sfValidatorInteger(array('required' => false)),
      'super_class_indexed'          => new sfValidatorString(array('required' => false)),
      'class_ref'                    => new sfValidatorInteger(array('required' => false)),
      'class_indexed'                => new sfValidatorString(array('required' => false)),
      'sub_class_ref'                => new sfValidatorInteger(array('required' => false)),
      'sub_class_indexed'            => new sfValidatorString(array('required' => false)),
      'infra_class_ref'              => new sfValidatorInteger(array('required' => false)),
      'infra_class_indexed'          => new sfValidatorString(array('required' => false)),
      'super_division_ref'           => new sfValidatorInteger(array('required' => false)),
      'super_division_indexed'       => new sfValidatorString(array('required' => false)),
      'division_ref'                 => new sfValidatorInteger(array('required' => false)),
      'division_indexed'             => new sfValidatorString(array('required' => false)),
      'sub_division_ref'             => new sfValidatorInteger(array('required' => false)),
      'sub_division_indexed'         => new sfValidatorString(array('required' => false)),
      'infra_division_ref'           => new sfValidatorInteger(array('required' => false)),
      'infra_division_indexed'       => new sfValidatorString(array('required' => false)),
      'super_legion_ref'             => new sfValidatorInteger(array('required' => false)),
      'super_legion_indexed'         => new sfValidatorString(array('required' => false)),
      'legion_ref'                   => new sfValidatorInteger(array('required' => false)),
      'legion_indexed'               => new sfValidatorString(array('required' => false)),
      'sub_legion_ref'               => new sfValidatorInteger(array('required' => false)),
      'sub_legion_indexed'           => new sfValidatorString(array('required' => false)),
      'infra_legion_ref'             => new sfValidatorInteger(array('required' => false)),
      'infra_legion_indexed'         => new sfValidatorString(array('required' => false)),
      'super_cohort_zoology_ref'     => new sfValidatorInteger(array('required' => false)),
      'super_cohort_zoology_indexed' => new sfValidatorString(array('required' => false)),
      'cohort_zoology_ref'           => new sfValidatorInteger(array('required' => false)),
      'cohort_zoology_indexed'       => new sfValidatorString(array('required' => false)),
      'sub_cohort_zoology_ref'       => new sfValidatorInteger(array('required' => false)),
      'sub_cohort_zoology_indexed'   => new sfValidatorString(array('required' => false)),
      'infra_cohort_zoology_ref'     => new sfValidatorInteger(array('required' => false)),
      'infra_cohort_zoology_indexed' => new sfValidatorString(array('required' => false)),
      'super_order_ref'              => new sfValidatorInteger(array('required' => false)),
      'super_order_indexed'          => new sfValidatorString(array('required' => false)),
      'order_ref'                    => new sfValidatorInteger(array('required' => false)),
      'order_indexed'                => new sfValidatorString(array('required' => false)),
      'sub_order_ref'                => new sfValidatorInteger(array('required' => false)),
      'sub_order_indexed'            => new sfValidatorString(array('required' => false)),
      'infra_order_ref'              => new sfValidatorInteger(array('required' => false)),
      'infra_order_indexed'          => new sfValidatorString(array('required' => false)),
      'section_zoology_ref'          => new sfValidatorInteger(array('required' => false)),
      'section_zoology_indexed'      => new sfValidatorString(array('required' => false)),
      'sub_section_zoology_ref'      => new sfValidatorInteger(array('required' => false)),
      'sub_section_zoology_indexed'  => new sfValidatorString(array('required' => false)),
      'super_family_ref'             => new sfValidatorInteger(array('required' => false)),
      'super_family_indexed'         => new sfValidatorString(array('required' => false)),
      'family_ref'                   => new sfValidatorInteger(array('required' => false)),
      'family_indexed'               => new sfValidatorString(array('required' => false)),
      'sub_family_ref'               => new sfValidatorInteger(array('required' => false)),
      'sub_family_indexed'           => new sfValidatorString(array('required' => false)),
      'infra_family_ref'             => new sfValidatorInteger(array('required' => false)),
      'infra_family_indexed'         => new sfValidatorString(array('required' => false)),
      'super_tribe_ref'              => new sfValidatorInteger(array('required' => false)),
      'super_tribe_indexed'          => new sfValidatorString(array('required' => false)),
      'tribe_ref'                    => new sfValidatorInteger(array('required' => false)),
      'tribe_indexed'                => new sfValidatorString(array('required' => false)),
      'sub_tribe_ref'                => new sfValidatorInteger(array('required' => false)),
      'sub_tribe_indexed'            => new sfValidatorString(array('required' => false)),
      'infra_tribe_ref'              => new sfValidatorInteger(array('required' => false)),
      'infra_tribe_indexed'          => new sfValidatorString(array('required' => false)),
      'genus_ref'                    => new sfValidatorInteger(array('required' => false)),
      'genus_indexed'                => new sfValidatorString(array('required' => false)),
      'sub_genus_ref'                => new sfValidatorInteger(array('required' => false)),
      'sub_genus_indexed'            => new sfValidatorString(array('required' => false)),
      'section_botany_ref'           => new sfValidatorInteger(array('required' => false)),
      'section_botany_indexed'       => new sfValidatorString(array('required' => false)),
      'sub_section_botany_ref'       => new sfValidatorInteger(array('required' => false)),
      'sub_section_botany_indexed'   => new sfValidatorString(array('required' => false)),
      'serie_ref'                    => new sfValidatorInteger(array('required' => false)),
      'serie_indexed'                => new sfValidatorString(array('required' => false)),
      'sub_serie_ref'                => new sfValidatorInteger(array('required' => false)),
      'sub_serie_indexed'            => new sfValidatorString(array('required' => false)),
      'super_species_ref'            => new sfValidatorInteger(array('required' => false)),
      'super_species_indexed'        => new sfValidatorString(array('required' => false)),
      'species_ref'                  => new sfValidatorInteger(array('required' => false)),
      'species_indexed'              => new sfValidatorString(array('required' => false)),
      'sub_species_ref'              => new sfValidatorInteger(array('required' => false)),
      'sub_species_indexed'          => new sfValidatorString(array('required' => false)),
      'variety_ref'                  => new sfValidatorInteger(array('required' => false)),
      'variety_indexed'              => new sfValidatorString(array('required' => false)),
      'sub_variety_ref'              => new sfValidatorInteger(array('required' => false)),
      'sub_variety_indexed'          => new sfValidatorString(array('required' => false)),
      'form_ref'                     => new sfValidatorInteger(array('required' => false)),
      'form_indexed'                 => new sfValidatorString(array('required' => false)),
      'sub_form_ref'                 => new sfValidatorInteger(array('required' => false)),
      'sub_form_indexed'             => new sfValidatorString(array('required' => false)),
      'abberans_ref'                 => new sfValidatorInteger(array('required' => false)),
      'abberans_indexed'             => new sfValidatorString(array('required' => false)),
      'extinct'                      => new sfValidatorBoolean(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('taxonomy[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Taxonomy';
  }

}
