<?php

/**
 * Taxonomy form base class.
 *
 * @package    form
 * @subpackage taxonomy
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 8508 2008-04-17 17:39:15Z fabien $
 */
class BaseTaxonomyForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id'                           => new sfWidgetFormInputHidden(),
      'name'                         => new sfWidgetFormTextarea(),
      'name_indexed'                 => new sfWidgetFormTextarea(),
      'description_year'             => new sfWidgetFormInput(),
      'description_year_compl'       => new sfWidgetFormInput(),
      'level_ref'                    => new sfWidgetFormInput(),
      'status'                       => new sfWidgetFormTextarea(),
      'path'                         => new sfWidgetFormTextarea(),
      'parent_ref'                   => new sfWidgetFormDoctrineChoice(array('model' => 'Taxonomy', 'add_empty' => false)),
      'domain_ref'                   => new sfWidgetFormInput(),
      'domain_indexed'               => new sfWidgetFormTextarea(),
      'kingdom_ref'                  => new sfWidgetFormInput(),
      'kingdom_indexed'              => new sfWidgetFormTextarea(),
      'super_phylum_ref'             => new sfWidgetFormInput(),
      'super_phylum_indexed'         => new sfWidgetFormTextarea(),
      'phylum_ref'                   => new sfWidgetFormInput(),
      'phylum_indexed'               => new sfWidgetFormTextarea(),
      'sub_phylum_ref'               => new sfWidgetFormInput(),
      'sub_phylum_indexed'           => new sfWidgetFormTextarea(),
      'infra_phylum_ref'             => new sfWidgetFormInput(),
      'infra_phylum_indexed'         => new sfWidgetFormTextarea(),
      'super_cohort_botany_ref'      => new sfWidgetFormInput(),
      'super_cohort_botany_indexed'  => new sfWidgetFormTextarea(),
      'cohort_botany_ref'            => new sfWidgetFormInput(),
      'cohort_botany_indexed'        => new sfWidgetFormTextarea(),
      'sub_cohort_botany_ref'        => new sfWidgetFormInput(),
      'sub_cohort_botany_indexed'    => new sfWidgetFormTextarea(),
      'infra_cohort_botany_ref'      => new sfWidgetFormInput(),
      'infra_cohort_botany_indexed'  => new sfWidgetFormTextarea(),
      'super_class_ref'              => new sfWidgetFormInput(),
      'super_class_indexed'          => new sfWidgetFormTextarea(),
      'class_ref'                    => new sfWidgetFormInput(),
      'class_indexed'                => new sfWidgetFormTextarea(),
      'sub_class_ref'                => new sfWidgetFormInput(),
      'sub_class_indexed'            => new sfWidgetFormTextarea(),
      'infra_class_ref'              => new sfWidgetFormInput(),
      'infra_class_indexed'          => new sfWidgetFormTextarea(),
      'super_division_ref'           => new sfWidgetFormInput(),
      'super_division_indexed'       => new sfWidgetFormTextarea(),
      'division_ref'                 => new sfWidgetFormInput(),
      'division_indexed'             => new sfWidgetFormTextarea(),
      'sub_division_ref'             => new sfWidgetFormInput(),
      'sub_division_indexed'         => new sfWidgetFormTextarea(),
      'infra_division_ref'           => new sfWidgetFormInput(),
      'infra_division_indexed'       => new sfWidgetFormTextarea(),
      'super_legion_ref'             => new sfWidgetFormInput(),
      'super_legion_indexed'         => new sfWidgetFormTextarea(),
      'legion_ref'                   => new sfWidgetFormInput(),
      'legion_indexed'               => new sfWidgetFormTextarea(),
      'sub_legion_ref'               => new sfWidgetFormInput(),
      'sub_legion_indexed'           => new sfWidgetFormTextarea(),
      'infra_legion_ref'             => new sfWidgetFormInput(),
      'infra_legion_indexed'         => new sfWidgetFormTextarea(),
      'super_cohort_zoology_ref'     => new sfWidgetFormInput(),
      'super_cohort_zoology_indexed' => new sfWidgetFormTextarea(),
      'cohort_zoology_ref'           => new sfWidgetFormInput(),
      'cohort_zoology_indexed'       => new sfWidgetFormTextarea(),
      'sub_cohort_zoology_ref'       => new sfWidgetFormInput(),
      'sub_cohort_zoology_indexed'   => new sfWidgetFormTextarea(),
      'infra_cohort_zoology_ref'     => new sfWidgetFormInput(),
      'infra_cohort_zoology_indexed' => new sfWidgetFormTextarea(),
      'super_order_ref'              => new sfWidgetFormInput(),
      'super_order_indexed'          => new sfWidgetFormTextarea(),
      'order_ref'                    => new sfWidgetFormInput(),
      'order_indexed'                => new sfWidgetFormTextarea(),
      'sub_order_ref'                => new sfWidgetFormInput(),
      'sub_order_indexed'            => new sfWidgetFormTextarea(),
      'infra_order_ref'              => new sfWidgetFormInput(),
      'infra_order_indexed'          => new sfWidgetFormTextarea(),
      'section_zoology_ref'          => new sfWidgetFormInput(),
      'section_zoology_indexed'      => new sfWidgetFormTextarea(),
      'sub_section_zoology_ref'      => new sfWidgetFormInput(),
      'sub_section_zoology_indexed'  => new sfWidgetFormTextarea(),
      'super_family_ref'             => new sfWidgetFormInput(),
      'super_family_indexed'         => new sfWidgetFormTextarea(),
      'family_ref'                   => new sfWidgetFormInput(),
      'family_indexed'               => new sfWidgetFormTextarea(),
      'sub_family_ref'               => new sfWidgetFormInput(),
      'sub_family_indexed'           => new sfWidgetFormTextarea(),
      'infra_family_ref'             => new sfWidgetFormInput(),
      'infra_family_indexed'         => new sfWidgetFormTextarea(),
      'super_tribe_ref'              => new sfWidgetFormInput(),
      'super_tribe_indexed'          => new sfWidgetFormTextarea(),
      'tribe_ref'                    => new sfWidgetFormInput(),
      'tribe_indexed'                => new sfWidgetFormTextarea(),
      'sub_tribe_ref'                => new sfWidgetFormInput(),
      'sub_tribe_indexed'            => new sfWidgetFormTextarea(),
      'infra_tribe_ref'              => new sfWidgetFormInput(),
      'infra_tribe_indexed'          => new sfWidgetFormTextarea(),
      'genus_ref'                    => new sfWidgetFormInput(),
      'genus_indexed'                => new sfWidgetFormTextarea(),
      'sub_genus_ref'                => new sfWidgetFormInput(),
      'sub_genus_indexed'            => new sfWidgetFormTextarea(),
      'section_botany_ref'           => new sfWidgetFormInput(),
      'section_botany_indexed'       => new sfWidgetFormTextarea(),
      'sub_section_botany_ref'       => new sfWidgetFormInput(),
      'sub_section_botany_indexed'   => new sfWidgetFormTextarea(),
      'serie_ref'                    => new sfWidgetFormInput(),
      'serie_indexed'                => new sfWidgetFormTextarea(),
      'sub_serie_ref'                => new sfWidgetFormInput(),
      'sub_serie_indexed'            => new sfWidgetFormTextarea(),
      'super_species_ref'            => new sfWidgetFormInput(),
      'super_species_indexed'        => new sfWidgetFormTextarea(),
      'species_ref'                  => new sfWidgetFormInput(),
      'species_indexed'              => new sfWidgetFormTextarea(),
      'sub_species_ref'              => new sfWidgetFormInput(),
      'sub_species_indexed'          => new sfWidgetFormTextarea(),
      'variety_ref'                  => new sfWidgetFormInput(),
      'variety_indexed'              => new sfWidgetFormTextarea(),
      'sub_variety_ref'              => new sfWidgetFormInput(),
      'sub_variety_indexed'          => new sfWidgetFormTextarea(),
      'form_ref'                     => new sfWidgetFormInput(),
      'form_indexed'                 => new sfWidgetFormTextarea(),
      'sub_form_ref'                 => new sfWidgetFormInput(),
      'sub_form_indexed'             => new sfWidgetFormTextarea(),
      'abberans_ref'                 => new sfWidgetFormInput(),
      'abberans_indexed'             => new sfWidgetFormTextarea(),
      'chimera_hybrid_pos'           => new sfWidgetFormTextarea(),
      'extinct'                      => new sfWidgetFormInputCheckbox(),
    ));

    $this->setValidators(array(
      'id'                           => new sfValidatorDoctrineChoice(array('model' => 'Taxonomy', 'column' => 'id', 'required' => false)),
      'name'                         => new sfValidatorString(array('max_length' => 2147483647)),
      'name_indexed'                 => new sfValidatorString(array('max_length' => 2147483647, 'required' => false)),
      'description_year'             => new sfValidatorInteger(array('required' => false)),
      'description_year_compl'       => new sfValidatorString(array('max_length' => 2, 'required' => false)),
      'level_ref'                    => new sfValidatorInteger(array('required' => false)),
      'status'                       => new sfValidatorString(array('max_length' => 2147483647)),
      'path'                         => new sfValidatorString(array('max_length' => 2147483647)),
      'parent_ref'                   => new sfValidatorDoctrineChoice(array('model' => 'Taxonomy')),
      'domain_ref'                   => new sfValidatorInteger(),
      'domain_indexed'               => new sfValidatorString(array('max_length' => 2147483647)),
      'kingdom_ref'                  => new sfValidatorInteger(),
      'kingdom_indexed'              => new sfValidatorString(array('max_length' => 2147483647)),
      'super_phylum_ref'             => new sfValidatorInteger(),
      'super_phylum_indexed'         => new sfValidatorString(array('max_length' => 2147483647)),
      'phylum_ref'                   => new sfValidatorInteger(),
      'phylum_indexed'               => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_phylum_ref'               => new sfValidatorInteger(),
      'sub_phylum_indexed'           => new sfValidatorString(array('max_length' => 2147483647)),
      'infra_phylum_ref'             => new sfValidatorInteger(),
      'infra_phylum_indexed'         => new sfValidatorString(array('max_length' => 2147483647)),
      'super_cohort_botany_ref'      => new sfValidatorInteger(),
      'super_cohort_botany_indexed'  => new sfValidatorString(array('max_length' => 2147483647)),
      'cohort_botany_ref'            => new sfValidatorInteger(),
      'cohort_botany_indexed'        => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_cohort_botany_ref'        => new sfValidatorInteger(),
      'sub_cohort_botany_indexed'    => new sfValidatorString(array('max_length' => 2147483647)),
      'infra_cohort_botany_ref'      => new sfValidatorInteger(),
      'infra_cohort_botany_indexed'  => new sfValidatorString(array('max_length' => 2147483647)),
      'super_class_ref'              => new sfValidatorInteger(),
      'super_class_indexed'          => new sfValidatorString(array('max_length' => 2147483647)),
      'class_ref'                    => new sfValidatorInteger(),
      'class_indexed'                => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_class_ref'                => new sfValidatorInteger(),
      'sub_class_indexed'            => new sfValidatorString(array('max_length' => 2147483647)),
      'infra_class_ref'              => new sfValidatorInteger(),
      'infra_class_indexed'          => new sfValidatorString(array('max_length' => 2147483647)),
      'super_division_ref'           => new sfValidatorInteger(),
      'super_division_indexed'       => new sfValidatorString(array('max_length' => 2147483647)),
      'division_ref'                 => new sfValidatorInteger(),
      'division_indexed'             => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_division_ref'             => new sfValidatorInteger(),
      'sub_division_indexed'         => new sfValidatorString(array('max_length' => 2147483647)),
      'infra_division_ref'           => new sfValidatorInteger(),
      'infra_division_indexed'       => new sfValidatorString(array('max_length' => 2147483647)),
      'super_legion_ref'             => new sfValidatorInteger(),
      'super_legion_indexed'         => new sfValidatorString(array('max_length' => 2147483647)),
      'legion_ref'                   => new sfValidatorInteger(),
      'legion_indexed'               => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_legion_ref'               => new sfValidatorInteger(),
      'sub_legion_indexed'           => new sfValidatorString(array('max_length' => 2147483647)),
      'infra_legion_ref'             => new sfValidatorInteger(),
      'infra_legion_indexed'         => new sfValidatorString(array('max_length' => 2147483647)),
      'super_cohort_zoology_ref'     => new sfValidatorInteger(),
      'super_cohort_zoology_indexed' => new sfValidatorString(array('max_length' => 2147483647)),
      'cohort_zoology_ref'           => new sfValidatorInteger(),
      'cohort_zoology_indexed'       => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_cohort_zoology_ref'       => new sfValidatorInteger(),
      'sub_cohort_zoology_indexed'   => new sfValidatorString(array('max_length' => 2147483647)),
      'infra_cohort_zoology_ref'     => new sfValidatorInteger(),
      'infra_cohort_zoology_indexed' => new sfValidatorString(array('max_length' => 2147483647)),
      'super_order_ref'              => new sfValidatorInteger(),
      'super_order_indexed'          => new sfValidatorString(array('max_length' => 2147483647)),
      'order_ref'                    => new sfValidatorInteger(),
      'order_indexed'                => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_order_ref'                => new sfValidatorInteger(),
      'sub_order_indexed'            => new sfValidatorString(array('max_length' => 2147483647)),
      'infra_order_ref'              => new sfValidatorInteger(),
      'infra_order_indexed'          => new sfValidatorString(array('max_length' => 2147483647)),
      'section_zoology_ref'          => new sfValidatorInteger(),
      'section_zoology_indexed'      => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_section_zoology_ref'      => new sfValidatorInteger(),
      'sub_section_zoology_indexed'  => new sfValidatorString(array('max_length' => 2147483647)),
      'super_family_ref'             => new sfValidatorInteger(),
      'super_family_indexed'         => new sfValidatorString(array('max_length' => 2147483647)),
      'family_ref'                   => new sfValidatorInteger(),
      'family_indexed'               => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_family_ref'               => new sfValidatorInteger(),
      'sub_family_indexed'           => new sfValidatorString(array('max_length' => 2147483647)),
      'infra_family_ref'             => new sfValidatorInteger(),
      'infra_family_indexed'         => new sfValidatorString(array('max_length' => 2147483647)),
      'super_tribe_ref'              => new sfValidatorInteger(),
      'super_tribe_indexed'          => new sfValidatorString(array('max_length' => 2147483647)),
      'tribe_ref'                    => new sfValidatorInteger(),
      'tribe_indexed'                => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_tribe_ref'                => new sfValidatorInteger(),
      'sub_tribe_indexed'            => new sfValidatorString(array('max_length' => 2147483647)),
      'infra_tribe_ref'              => new sfValidatorInteger(),
      'infra_tribe_indexed'          => new sfValidatorString(array('max_length' => 2147483647)),
      'genus_ref'                    => new sfValidatorInteger(),
      'genus_indexed'                => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_genus_ref'                => new sfValidatorInteger(),
      'sub_genus_indexed'            => new sfValidatorString(array('max_length' => 2147483647)),
      'section_botany_ref'           => new sfValidatorInteger(),
      'section_botany_indexed'       => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_section_botany_ref'       => new sfValidatorInteger(),
      'sub_section_botany_indexed'   => new sfValidatorString(array('max_length' => 2147483647)),
      'serie_ref'                    => new sfValidatorInteger(),
      'serie_indexed'                => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_serie_ref'                => new sfValidatorInteger(),
      'sub_serie_indexed'            => new sfValidatorString(array('max_length' => 2147483647)),
      'super_species_ref'            => new sfValidatorInteger(),
      'super_species_indexed'        => new sfValidatorString(array('max_length' => 2147483647)),
      'species_ref'                  => new sfValidatorInteger(),
      'species_indexed'              => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_species_ref'              => new sfValidatorInteger(),
      'sub_species_indexed'          => new sfValidatorString(array('max_length' => 2147483647)),
      'variety_ref'                  => new sfValidatorInteger(),
      'variety_indexed'              => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_variety_ref'              => new sfValidatorInteger(),
      'sub_variety_indexed'          => new sfValidatorString(array('max_length' => 2147483647)),
      'form_ref'                     => new sfValidatorInteger(),
      'form_indexed'                 => new sfValidatorString(array('max_length' => 2147483647)),
      'sub_form_ref'                 => new sfValidatorInteger(),
      'sub_form_indexed'             => new sfValidatorString(array('max_length' => 2147483647)),
      'abberans_ref'                 => new sfValidatorInteger(),
      'abberans_indexed'             => new sfValidatorString(array('max_length' => 2147483647)),
      'chimera_hybrid_pos'           => new sfValidatorString(array('max_length' => 2147483647)),
      'extinct'                      => new sfValidatorBoolean(),
    ));

    $this->widgetSchema->setNameFormat('taxonomy[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'Taxonomy';
  }

}
