<?php 
include(dirname(__FILE__).'/../../bootstrap/Doctrine.php');
$t = new lime_test(23, new lime_output_color());

$t->info('Get all levels');
$levels = Doctrine::getTable('CatalogueLevels')->getLevelsByTypes(array());
$t->is($levels->count(),77,'There are a good number of levels');
$t->is($levels[76]->getLevelName(),'rock','Name of last level is well "rock"');
$t->info('Get levels for Taxonomy');
$levels = Doctrine::getTable('CatalogueLevels')->getLevelsByTypes(array('table'=>'taxonomy'));
$t->is($levels->count(),54,'There are "54" results in taxonomy');
$t->is($levels[0]->getLevelName(),'domain','The first one is "domain"');
$t->info('Get levels for Chronostratigraphy');
$levels = Doctrine::getTable('CatalogueLevels')->getLevelsByTypes(array('table'=>'chronostratigraphy'));
$t->is($levels->count(),9,'There are "9" results in chronostratigraphy');
$t->is($levels[0]->getLevelName(),'eon','The first one is "eon"');
$t->info('Get levels for Lithostratigraphy');
$levels = Doctrine::getTable('CatalogueLevels')->getLevelsByTypes(array('table'=>'lithostratigraphy'));
$t->is($levels->count(),6,'There are "6" results in lithostratigraphy');
$t->is($levels[0]->getLevelName(),'group','The first one is "group"');
$t->info('Get levels for Lithology');
$levels = Doctrine::getTable('CatalogueLevels')->getLevelsByTypes(array('table'=>'lithology'));
$t->is($levels->count(),4,'There are "4" results in lithology');
$t->is($levels[0]->getLevelName(),'main group','The first one is "main group"');
$t->info('Get levels for Mineralogy');
$levels = Doctrine::getTable('CatalogueLevels')->getLevelsByTypes(array('table'=>'mineralogy'));
$t->is($levels->count(),4,'There are "4" results in mineralogy');
$t->is($levels[0]->getLevelName(),'class','The first one is "class"');
$t->info('Get possible upper levels for taxonomical species');
$levels = Doctrine::getTable('CatalogueLevels')->getLevelsByTypes(array('table'=>'taxonomy', 'level'=>48));
$t->is($levels->count(),25,'There are "25" results for possible parents of a "species"');
$t->is($levels[0]->getLevelName(),'phylum','The first one is "phylum"');
$t->is($levels[6]->getLevelName(),'order','The last one is "order"');
$t->info('Get possible upper levels for chronostratigraphical stage');
$levels = Doctrine::getTable('CatalogueLevels')->getLevelsByTypes(array('table'=>'chronostratigraphy', 'level'=>60));
$t->is($levels->count(),1,'There is "1" results for possible parents of a "stage"');
$t->is($levels[0]->getLevelName(),'serie','The first and only one is "serie"');
$t->info('Get possible upper levels for lithostratigraphical layer');
$levels = Doctrine::getTable('CatalogueLevels')->getLevelsByTypes(array('table'=>'lithostratigraphy', 'level'=>67));
$t->is($levels->count(),1,'There is "1" results for possible parents of a "layer"');
$t->is($levels[0]->getLevelName(),'member','The first and only one is "member"');
$t->info('Get possible upper levels for lithology sub group');
$levels = Doctrine::getTable('CatalogueLevels')->getLevelsByTypes(array('table'=>'lithology', 'level'=>77));
$t->is($levels->count(),1,'There is "1" results for possible parents of a "sub group"');
$t->is($levels[0]->getLevelName(),'group','The first and only one is "group"');
$t->info('Get possible upper levels for mineralogy series');
$levels = Doctrine::getTable('CatalogueLevels')->getLevelsByTypes(array('table'=>'mineralogy', 'level'=>72));
$t->is($levels->count(),1,'There is "1" results for possible parents of a "sub_group"');
$t->is($levels[0]->getLevelName(),'sub_class','The first and only one is "series"');